### ISSUE TITLE
Best practices vkFreeMemory() crashes if memory is VK_NULL_HANDLE

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-ValidationLayers#1478]
If the best practices layer is enabled, `vkFreeMemory()` crashes if `memory==VK_NULL_HANDLE`.

From the spec:
> If memory is not VK_NULL_HANDLE, memory must be a valid VkDeviceMemory handle

Stacktrace:
```
#0  0x00007fffd1807f8d in std::_Hashtable<VkDeviceMemory_T*, std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> >, std::allocator<std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> > >, std::__detail::_Select1st, std::equal_to<VkDeviceMemory_T*>, std::hash<VkDeviceMemory_T*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node(unsigned long, VkDeviceMemory_T* const&, unsigned long) const (__code=0, __k=<optimized out>, __n=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/hashtable.h:1436
#1  0x00007fffd1807f8d in std::_Hashtable<VkDeviceMemory_T*, std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> >, std::allocator<std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> > >, std::__detail::_Select1st, std::equal_to<VkDeviceMemory_T*>, std::hash<VkDeviceMemory_T*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node(unsigned long, VkDeviceMemory_T* const&, unsigned long) const
    (__c=0, __key=<optimized out>, __bkt=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/hashtable.h:632
#2  0x00007fffd1807f8d in std::_Hashtable<VkDeviceMemory_T*, std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> >, std::allocator<std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> > >, std::__detail::_Select1st, std::equal_to<VkDeviceMemory_T*>, std::hash<VkDeviceMemory_T*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(VkDeviceMemory_T* const&) const
    (__k=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/hashtable.h:1323
#3  0x00007fffd1807f8d in std::unordered_map<VkDeviceMemory_T*, std::shared_ptr<DEVICE_MEMORY_STATE>, std::hash<VkDeviceMemory_T*>, std::equal_to<VkDeviceMemory_T*>, std::allocator<std::pair<VkDeviceMemory_T* const, std::shared_ptr<DEVICE_MEMORY_STATE> > > >::find(VkDeviceMemory_T* const&) const (__x=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/unordered_map.h:619
#4  0x00007fffd1807f8d in ValidationStateTracker::Get<DEVICE_MEMORY_STATE>(ValidationStateTracker::AccessorTraits<DEVICE_MEMORY_STATE, int>::HandleType) const (handle=<optimized out>, this=<optimized out>)
    at /root/sdk-build/1.1.130.0/source/Vulkan-ValidationLayers/layers/state_tracker.h:317
#5  0x00007fffd1807f8d in ValidationStateTracker::GetDevMemState(VkDeviceMemory_T*) const (mem=<optimized out>, this=<optimized out>) at /root/sdk-build/1.1.130.0/source/Vulkan-ValidationLayers/layers/state_tracker.h:417
#6  0x00007fffd1807f8d in BestPractices::PreCallValidateFreeMemory(VkDevice_T*, VkDeviceMemory_T*, VkAllocationCallbacks const*) const (this=0x555556073fc0, device=<optimized out>, memory=0x0, pAllocator=<optimized out>)
    at /root/sdk-build/1.1.130.0/source/Vulkan-ValidationLayers/layers/best_practices.cpp:261
#7  0x00007fffd154558f in vulkan_layer_chassis::FreeMemory(VkDevice_T*, VkDeviceMemory_T*, VkAllocationCallbacks const*) (device=0x555556077540, memory=0x0, pAllocator=0x0) at /root/sdk-build/1.1.130.0/source/Vulkan-ValidationLayers/layers/generated/chassis.cpp:1314
<application code>
```

**Comment by mark-lunarg** [comment]
Fixed by PR #1480.  Thanks!
