### ISSUE TITLE
Crash inside validation of vkCmdClearAttachment with imagelessFramebuffer

### ISSUE THREAD

**Issue by ascent12** [KhronosGroup/Vulkan-ValidationLayers#1780]
Version: 1.2.135
API Version: 1.2
OS: Archlinux

I get a crash with a null pointer dereference inside of the validation layers when I call `vkCmdClearAttachment` while using the `imagelessFramebuffer` feature. If I disable the validation layers, the code runs correctly and as expected.

```
(gdb) bt
#0  0x00007f853d122ea0 in CoreChecks::ValidateClearAttachmentExtent (this=0x563b5049fa90, command_buffer=0x563b50a30f00, 
    attachment_index=0, framebuffer=<optimized out>, fb_attachment=0, render_area=..., rect_count=1, clear_rects=0x7ffd85fd1dc0)
    at /usr/src/debug/Vulkan-ValidationLayers-1.2.135/layers/buffer_validation.cpp:2746
#1  0x00007f853d12d069 in CoreChecks::PreCallValidateCmdClearAttachments (this=<optimized out>, commandBuffer=0x563b50a30f00, 
    attachmentCount=<optimized out>, pAttachments=<optimized out>, rectCount=<optimized out>, pRects=<optimized out>)
    at /usr/src/debug/Vulkan-ValidationLayers-1.2.135/layers/buffer_validation.cpp:2848
#2  0x00007f853cfa3a40 in vulkan_layer_chassis::CmdClearAttachments (commandBuffer=0x563b50a30f00, attachmentCount=1, 
    pAttachments=0x563b4ebe3ba0 <clear>, rectCount=1, pRects=0x7ffd85fd1dc0)
    at /usr/src/debug/Vulkan-ValidationLayers-1.2.135/layers/generated/chassis.cpp:3550
#3  0x0000563b4ebe0c90 in vulkan_surface_repaint (surf=0x563b503d26e8, scene=0x563b50879460) at ../vulkan-surface.c:561
#4  0x0000563b4ebde160 in wayland_toplevel_repaint (surf=0x563b503d2670, data=0x563b503d2670) at ../wayland-surface.c:172
#5  0x0000563b4ebddda1 in wayland_surface_repaint (surf=0x563b503d2670) at ../wayland-surface.c:40
#6  0x0000563b4ebde029 in wayland_surface_schedule_repaint (surf=0x563b503d2670) at ../wayland-surface.c:135
#7  0x0000563b4ebdbbf4 in main () at ../main.c:319
(gdb) list CoreChecks::ValidateClearAttachmentExtent
2737	}
2738	
2739	bool CoreChecks::ValidateClearAttachmentExtent(VkCommandBuffer command_buffer, uint32_t attachment_index,
2740	                                               const FRAMEBUFFER_STATE *framebuffer, uint32_t fb_attachment,
2741	                                               const VkRect2D &render_area, uint32_t rect_count,
2742	                                               const VkClearRect *clear_rects) const {
2743	    bool skip = false;
2744	    const IMAGE_VIEW_STATE *image_view_state = nullptr;
2745	    if (framebuffer && (fb_attachment != VK_ATTACHMENT_UNUSED) && (fb_attachment < framebuffer->createInfo.attachmentCount)) {
2746	        image_view_state = GetImageViewState(framebuffer->createInfo.pAttachments[fb_attachment]);
```
Relevant parts from my code
```c
const VkFramebufferAttachmentImageInfo attach = {
	.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO,
	.flags = 0,
	.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
	.width = width,
	.height = height,
	.layerCount = 1,
	.viewFormatCount = 1,
	.pViewFormats = &format,
};
const VkFramebufferAttachmentsCreateInfo attach_info = {
	.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO,
	.attachmentImageInfoCount = 1,
	.pAttachmentImageInfos = &attach,
};
const VkFramebufferCreateInfo info = {
	.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
	.pNext = &attach_info,
	.flags = VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT,
	.renderPass = vk->renderpass.renderpass,
	.attachmentCount = 1,
	.pAttachments = NULL,
	.width = width,
	.height = height,
	.layers = 1,
};

res = vkCreateFramebuffer(vk->logical_device,
			  &info,
			  NULL,
			  &surf->framebuffer);
```
```c
const VkRenderPassAttachmentBeginInfo attach = {
	.sType = VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO,
	.attachmentCount = 1,
	.pAttachments = &img->image_view,
};
const VkRenderPassBeginInfo rp_info = {
	.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
	.pNext = &attach,
	.renderPass = vk->renderpass.renderpass,
	.framebuffer = surf->framebuffer,
	.renderArea.offset.x = 0,
	.renderArea.offset.y = 0,
	.renderArea.extent.width = surf->width,
	.renderArea.extent.height = surf->height,
	.clearValueCount = 0,
	.pClearValues = NULL,
};

/* This works fine, and nothing complains */
vkCmdBeginRenderPass(frame->command_buffer, &rp_info,
		     VK_SUBPASS_CONTENTS_INLINE);
```
The image/imageview comes from a swapchain image, but I don't think it affects this.
```c
/* Later in the render pass */
static const VkClearAttachment clear = {
	.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
	.colorAttachment = 0,
	.clearValue.color.float32 = { 0.8f, 0.8f, 0.8f, 0.8f },
};
const VkClearRect clear_rect = {
	.rect = rp_info.renderArea,
	.baseArrayLayer = 0,
	.layerCount = 1,
};
/* This is where it crashes */
vkCmdClearAttachments(frame->command_buffer,
		      1, &clear, 1, &clear_rect);
```

My guess is that validation layer is not ignoring `VkFramebufferCreateInfo::pAttachments` when `VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT` is set, as the spec says it should.

**Comment by Tony-LunarG** [comment]
I believe this is fixed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1759
Can you try a build beyond that commit and see if it fixes your problem?
