### ISSUE TITLE
Segfault on vkDestroyDevice when enabling GPU-assisted validation without the required features

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-ValidationLayers#1787]
If I enable GPU-assisted validation (via `VkInstanceCreateInfo`), e.g.

```c
    VkValidationFeaturesEXT vinfo = {
        .sType = VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT,
        .enabledValidationFeatureCount = 1,
        .pEnabledValidationFeatures = (VkValidationFeatureEnableEXT[]) {
            VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT,
        }
    };
```

but I forget to enable the required device-level features (`fragmentStoresAndAtomics` and `vertexPipelineStoresAndAtomics`, the layer will report the following on stderr:

```
UNASSIGNED-GPU-Assisted Validation Error. (ERROR / SPEC): msgNum: -157854676 - Validation Error: [ UNASSIGNED-GPU-Assisted Validation Error.  ] Object 0: handle = 0x9898989898989898, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf697542c | Detail: (GPU-Assisted validation requires fragmentStoresAndAtomics and vertexPipelineStoresAndAtomics.  GPU-Assisted Validation disabled.)
    Objects: 1
        [0] 0x9898989898989898, type: 3, name: NULL
```

But despite the assurance that "GPU-Assisted Validation [is] disabled", this layer will segfault on `vkDestroyDevice`:

```
Thread 1 "test.vulkan.c" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff69d1740 (LWP 2641784)]
0x00007fffefe95f7e in DispatchDestroyDescriptorSetLayout (device=0x5b5b5b5b5b5b5b5b, 
    descriptorSetLayout=0x5b5b5b5b5b5b5b5b, pAllocator=0x0)
    at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/generated/layer_chassis_dispatch.cpp:2272
2272	{
(gdb) bt
#0  0x00007fffefe95f7e in DispatchDestroyDescriptorSetLayout (device=0x5b5b5b5b5b5b5b5b, 
    descriptorSetLayout=0x5b5b5b5b5b5b5b5b, pAllocator=0x0)
    at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/generated/layer_chassis_dispatch.cpp:2272
#1  0x00007fffeffb720c in UtilPreCallRecordDestroyDevice<GpuAssisted> (object_ptr=0x555555e9a8d0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_tree.h:211
#2  GpuAssisted::PreCallRecordDestroyDevice (this=0x555555e9a8d0, device=<optimized out>, pAllocator=<optimized out>)
    at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/gpu_validation.cpp:282
#3  0x00007fffefe291db in vulkan_layer_chassis::DestroyDevice (device=0x555555a05be0, pAllocator=pAllocator@entry=0x0)
    at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/generated/chassis.cpp:666
#4  0x00007ffff75870cb in loader_layer_destroy_device (
    destroyFunction=0x7fffefe290d0 <vulkan_layer_chassis::DestroyDevice(VkDevice_T*, VkAllocationCallbacks const*)>, 
    pAllocator=0x0, device=0x5555559d5030)
    at /usr/src/debug/media-libs/vulkan-loader-9999/vulkan-loader-9999/loader/loader.c:5674
#5  loader_layer_destroy_device (device=device@entry=0x555555a05be0, pAllocator=pAllocator@entry=0x0, 
    destroyFunction=0x7fffefe290d0 <vulkan_layer_chassis::DestroyDevice(VkDevice_T*, VkAllocationCallbacks const*)>)
    at /usr/src/debug/media-libs/vulkan-loader-9999/vulkan-loader-9999/loader/loader.c:5663
#6  0x00007ffff758d456 in vkDestroyDevice (pAllocator=0x0, device=0x555555a05be0)
    at /usr/src/debug/media-libs/vulkan-loader-9999/vulkan-loader-9999/loader/trampoline.c:794
#7  vkDestroyDevice (device=0x555555a05be0, pAllocator=0x0) at /usr/include/vulkan/vulkan_core.h:3362
#8  0x000055555558e741 in pl_vulkan_destroy (pl_vk=0x7fffffffd4c0) at ../src/vulkan/context.c:587
#9  0x00005555555643f7 in main () at ../src/tests/vulkan.c:234
(gdb) 
```

Adding the required device-level features, or removing the validation features in question, makes it stop crashing.

**Comment by mark-lunarg** [comment]
@Tony-LunarG, this *may* be related to the new validation object init changes.  We need to talk about new tests for this kind of stuff as well.
