### ISSUE TITLE
Best Practices hitting segF

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#2018]
In recent ANGLE testing with the Best Practices layer I'm seeing a number of tests hitting a segF in BestPractices::PostCallRecordCmdBindPipeline() [best_practices_utils.cpp:1053](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blame/8f524e4908a6040f5205d113d0e294bcaef4b92d/layers/best_practices_utils.cpp#L1053)

One such example can be seen [here](https://chromium-swarm.appspot.com/task?id=4d49566d20ac4510#dEQP.KHR_GLES2%2Fcore_internalformat_renderbuffer_depth24_stencil8) for DEQP test dEQP.KHR_GLES2/core_internalformat_renderbuffer_depth24_stencil8.

In stepping through the code, it's clear that when the blend_state is loaded on line [1046](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blame/8f524e4908a6040f5205d113d0e294bcaef4b92d/layers/best_practices_utils.cpp#L1046), it's getting an incorrect attachmentCount, which seems to be garbage, causing the following loop to overstep the pAttachments array. I verified that the graphics pipeline for the test is created with an attachmentCount in the blendState of "1."

The repro is not too difficult. Follow the instructions on [ANGLE devsetup page](https://chromium.googlesource.com/angle/angle/+/master/doc/DevSetup.md) to clone and build Debug ANGLE.
After cloning ANGLE, but before building, cherry-pick my CL to enable Best Practices layer with:

> git fetch "https://chromium.googlesource.com/angle/angle" refs/changes/34/2202634/7 && git cherry-pick FETCH_HEAD

Then you can run the test given above with the command line:

> out\Debug\angle_deqp_khr_gles2_tests.exe --gtest_filter=dEQP.KHR_GLES2/core_internalformat_renderbuffer_depth24_stencil8

**Comment by mark-lunarg** [comment]
@tobine, does it pass running those CTS tests without Angle?

**Comment by tobine** [comment]
These are OpenGL dEQP tests so running without ANGLE just means running on a native OpenGL driver which is neither interesting for ANGLE or validation layers. More interesting is the fact that these tests pass with ANGLE when the Best Practices layer is not enabled. It it only the enabling of the Best Practices layer that causes them to fail.

**Comment by mark-lunarg** [comment]
Ah, OK, didn't doubt you, was just hoping for a simple, non-Angle repro case.

**Comment by haasn** [comment]
This crash is reproducible by the [libplacebo test suite](https://code.videolan.org/videolan/libplacebo).

backtrace
```gdb
(gdb) bt full
#0  0x00007ffff063cb9b in BestPractices::PostCallRecordCmdBindPipeline (this=0x555555a656d0, commandBuffer=<optimized out>, pipelineBindPoint=<optimized out>, pipeline=<optimized out>) at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/best_practices_utils.cpp:1053
        i = 284
        prepass_state = {
          <std::__detail::_Node_iterator_base<std::pair<VkCommandBuffer_T* const, BestPractices::DepthPrePassState>, false>> = {
            _M_cur = 0x555555fa0200
          }, <No data fields>}
        blend_state = 0x7fffffffcb00
        stencil_state = 0x0
        gp_cis = {
          <std::__detail::_Node_iterator_base<std::pair<VkPipeline_T* const, BestPractices::GraphicsPipelineCIs>, false>> = {
            _M_cur = 0x55555614fc70
          }, <No data fields>}
#1  0x00007ffff02e262e in vulkan_layer_chassis::CmdBindPipeline (commandBuffer=0x555555eb6240, pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline=0xa240000000a24) at /usr/src/debug/media-libs/vulkan-layers-9999/vulkan-layers-9999/layers/generated/chassis.cpp:3139
        lock = {
          _M_device = 0x555555a66870,
          _M_owns = true
        }
        intercept = 0x555555a656d0
        __for_range = std::vector of length 6, capacity 8 = {0x555555e0cff0, 0x555555a61430, 0x555555e5bce0, 0x555555a62bf0, 0x555555a656d0, 0x555555eabd90}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        layer_data = 0x555555a60100
        skip = false
#2  0x00005555555ae9ce in vk_pass_run (gpu=0x555555c0b6b0, params=0x7fffffffc810) at ../src/vulkan/gpu.c:2937
        p = 0x555555c0b7a0
        vk = 0x555555a35488
        pass = 0x555556193020
        pass_vk = 0x555556193128
        types = {GRAPHICS, GRAPHICS, COMPUTE}
        cmd = 0x555555eb6180
        __func__ = "vk_pass_run"
        ds = 0x0
        bindPoint = {VK_PIPELINE_BIND_POINT_GRAPHICS, VK_PIPELINE_BIND_POINT_GRAPHICS, VK_PIPELINE_BIND_POINT_COMPUTE}
        __PRETTY_FUNCTION__ = "vk_pass_run"
#3  0x0000555555579683 in pl_pass_run (gpu=0x555555c0b6b0, params=0x7fffffffc960) at ../src/gpu.c:1240
        pass = 0x555556193020
        new = {
          pass = 0x555556193020,
          var_updates = 0x0,
          num_var_updates = 0,
          desc_bindings = 0x0,
          push_constants = 0x0,
c          timer = 0x55555616b320,
          target = 0x55555609e780,
          viewport = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          scissors = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          vertex_count = 4,
          vertex_data = 0x0,
          vertex_buf = 0x555556180f20,
          buf_offset = 0,
          compute_groups = {0, 0, 0}
        }
        impl = 0x555555c0b7a0
#4  0x000055555557acb1 in pl_pass_run_vbo (gpu=0x555555c0b6b0, vbo=0x5555561931e8, params=0x7fffffffcbe0) at ../src/gpu.c:1560
        vert_size = 80
        vert = 0x555556180f20
        need_update = true
        cache = 0x555556180f70
        newparams = {
          pass = 0x555556193020,
          var_updates = 0x0,
          num_var_updates = 0,
          desc_bindings = 0x0,
          push_constants = 0x0,
          timer = 0x55555616b320,
          target = 0x55555609e780,
          viewport = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          scissors = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          vertex_count = 4,
          vertex_data = 0x0,
          vertex_buf = 0x555556180f20,
          buf_offset = 0,
          compute_groups = {0, 0, 0}
        }
#5  0x00005555555ae648 in vk_pass_run (gpu=0x555555c0b6b0, params=0x7fffffffcbe0) at ../src/vulkan/gpu.c:2883
        p = 0x555555c0b7a0
        vk = 0x555555a35488
        pass = 0x555556193020
        pass_vk = 0x555556193128
        types = {GRAPHICS, GRAPHICS, COMPUTE}
        cmd = 0x7ffff705c9e0 <main_arena>
        __func__ = "vk_pass_run"
        ds = 0x0
        bindPoint = {VK_PIPELINE_BIND_POINT_GRAPHICS, VK_PIPELINE_BIND_POINT_GRAPHICS, VK_PIPELINE_BIND_POINT_COMPUTE}
        __PRETTY_FUNCTION__ = "vk_pass_run"
#6  0x0000555555579683 in pl_pass_run (gpu=0x555555c0b6b0, params=0x7fffffffd1c0) at ../src/gpu.c:1240
        pass = 0x555556193020
        new = {
          pass = 0x555556193020,
          var_updates = 0x0,
          num_var_updates = 0,
          desc_bindings = 0x0,
          push_constants = 0x0,
          timer = 0x55555616b320,
          target = 0x55555609e780,
          viewport = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          scissors = {
            x0 = 0,
            y0 = 0,
            x1 = 16,
            y1 = 16
          },
          vertex_count = 4,
          vertex_data = 0x7fffffffd170,
          vertex_buf = 0x0,
          buf_offset = 0,
          compute_groups = {0, 0, 0}
        }
        impl = 0x555555c0b7a0
#7  0x00005555555601a2 in pl_shader_tests (gpu=0x555555c0b6b0) at ../src/tests/gpu_tests.h:294
        vert_shader = 0x5555555c6480 "#version 410", ' ' <repeats 31 times>, "\nlayout(location=0) in vec2 vertex_pos;     \nlayout(location=1) in vec3 vertex_color;   \nlayout(location=0) out vec3 frag_color;    \nvoid main() {", ' ' <repeats 11 times>...
        frag_shader = 0x5555555c65b8 "#version 410", ' ' <repeats 31 times>, "\nlayout(location=0) in vec3 frag_color;     \nlayout(location=0) out vec4 out_color;     \nvoid main() {", ' ' <repeats 30 times>, "\n    out_color = vec4(fra"...
        fbo_fmt = 0x555555a4d8f0
        caps = (PL_FMT_CAP_LINEAR | PL_FMT_CAP_RENDERABLE | PL_FMT_CAP_BLITTABLE)
        fbo = 0x55555609e780
        vert_fmt = 0x555555a4d830
        vertices = {{
            pos = {-1, -1},
            color = {0, 0, 0}
          }, {
            pos = {1, -1},
            color = {1, 0, 0}
          }, {
            pos = {-1, 1},
            color = {0, 1, 0}
--Type <RET> for more, q to quit, c to continue without paging--c
          }, {
            pos = {1, 1},
            color = {1, 1, 0}
          }}
        pass = 0x555556193020
        timer = 0x55555616b320
        data = {0 <repeats 1024 times>}
        dp = 0x0
        sh = 0x0
        src = 0x7fff00000003
        peak_state = 0x7fffffffcd70
        lut3d = 0x7ffff0331451 <std::unique_lock<ReadWriteLock>::unlock()+33>
        src_color = {
          color = {
            primaries = 121,
            transfer = PL_COLOR_TRC_UNKNOWN,
            light = 1436975888,
            sig_peak = 3.0611365e-41,
            sig_avg = 2.76334505e+13,
            sig_scale = 3.0611365e-41
          },
          profile = {
            data = 0x555555c90f40,
            len = 93824997328240,
            signature = 189534857993644544
          }
        }
        dst_color = {
          color = {
            primaries = 4150140880,
            transfer = 32767,
            light = 1440796656,
            sig_peak = 3.0611365e-41,
            sig_avg = 0,
            sig_scale = 0
          },
          profile = {
            data = 0x0,
            len = 93825001377776,
            signature = 93825001377776
          }
        }
        out = {
          src_color = {
            primaries = PL_COLOR_PRIM_UNKNOWN,
            transfer = PL_COLOR_TRC_UNKNOWN,
            light = 4143075662,
            sig_peak = 4.59163468e-41,
            sig_avg = -nan(0x7fce90),
            sig_scale = 4.59163468e-41
          },
          dst_color = {
            primaries = 1432096527,
            transfer = 21845,
            light = 1436767368,
            sig_peak = 3.0611365e-41,
            sig_avg = 4.05432833e+13,
            sig_scale = 0
          }
        }
        grain = 0x555555c90f40
        custom = {
          prelude = 0x0,
          header = 0x5e00000000 <error: Cannot access memory at address 0x5e00000000>,
          body = 0x200000002 <error: Cannot access memory at address 0x200000002>,
          input = PL_SHADER_SIG_SAMPLER,
          output = PL_SHADER_SIG_SAMPLER,
          descriptors = 0x200000002,
          num_descriptors = 1436869680,
          variables = 0x0,
          num_variables = 0,
          vertex_attribs = 0x555555a4e430,
          num_vertex_attribs = 0,
          compute = false,
          compute_shmem = 0,
          compute_group_size = {0, 0},
          output_w = 0,
          output_h = 0
        }
#8  0x0000555555564bd9 in gpu_tests (gpu=0x555555c0b6b0) at ../src/tests/gpu_tests.h:935
No locals.
#9  0x0000555555565deb in main () at ../src/tests/vulkan.c:285
        params = {
          instance = 0x555555652860,
          get_proc_addr = 0x0,
          instance_params = 0x0,
          surface = 0x20000000002,
          device = 0x5555556480f0,
          device_name = 0x0,
          device_uuid = '\000' <repeats 15 times>,
          allow_software = false,
          async_transfer = true,
          async_compute = true,
          queue_count = 8,
          extensions = 0x0,
          num_extensions = 0,
          opt_extensions = 0x0,
          num_opt_extensions = 0,
          features = 0x0,
          blacklist_caps = 0,
          max_glsl_version = 0,
          disable_events = false,
          max_api_version = 0
        }
        iparams = {
          instance = 0x3b9eb200,
          get_proc_addr = 0x0,
          phys_device = 0x0,
          device = 0x19dfe69,
          extensions = 0x7fffffffd4a4,
          num_extensions = 0,
          queue_graphics = {
            index = 32767,
            count = 4160562200
          },
          queue_compute = {
            index = 32767,
            count = 4294956400
          },
          queue_transfer = {
            index = 32767,
            count = 4294956384
          },
          features = 0x7ffff6df42f0,
          blacklist_caps = 17,
          max_glsl_version = -10800,
          disable_events = 255,
          max_api_version = 0
        }
        vk2 = 0x7fffffffd444
        props = {
          apiVersion = 4202627,
          driverVersion = 83890275,
          vendorID = 4098,
          deviceID = 29471,
          deviceType = VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU,
          deviceName = "AMD RADV NAVI10 (ACO)", '\000' <repeats 234 times>,
          pipelineCacheUUID = "Y\031\352U]\377\261\"q\222\371\004\237,\324J",
          limits = {
            maxImageDimension1D = 16384,
            maxImageDimension2D = 16384,
            maxImageDimension3D = 2048,
            maxImageDimensionCube = 16384,
            maxImageArrayLayers = 2048,
            maxTexelBufferElements = 4294967295,
            maxUniformBufferRange = 4294967295,
            maxStorageBufferRange = 4294967295,
            maxPushConstantsSize = 128,
            maxMemoryAllocationCount = 4294967295,
            maxSamplerAllocationCount = 65536,
            bufferImageGranularity = 64,
            sparseAddressSpaceSize = 4294967292,
            maxBoundDescriptorSets = 31,
            maxPerStageDescriptorSamplers = 8388606,
            maxPerStageDescriptorUniformBuffers = 8388606,
            maxPerStageDescriptorStorageBuffers = 8388606,
            maxPerStageDescriptorSampledImages = 8388606,
            maxPerStageDescriptorStorageImages = 8388606,
            maxPerStageDescriptorInputAttachments = 8388606,
            maxPerStageResources = 8388606,
            maxDescriptorSetSamplers = 8388606,
            maxDescriptorSetUniformBuffers = 8388606,
            maxDescriptorSetUniformBuffersDynamic = 16,
            maxDescriptorSetStorageBuffers = 8388606,
            maxDescriptorSetStorageBuffersDynamic = 8,
            maxDescriptorSetSampledImages = 8388606,
            maxDescriptorSetStorageImages = 8388606,
            maxDescriptorSetInputAttachments = 8388606,
            maxVertexInputAttributes = 32,
            maxVertexInputBindings = 32,
            maxVertexInputAttributeOffset = 2047,
            maxVertexInputBindingStride = 2048,
            maxVertexOutputComponents = 128,
            maxTessellationGenerationLevel = 64,
            maxTessellationPatchSize = 32,
            maxTessellationControlPerVertexInputComponents = 128,
            maxTessellationControlPerVertexOutputComponents = 128,
            maxTessellationControlPerPatchOutputComponents = 120,
            maxTessellationControlTotalOutputComponents = 4096,
            maxTessellationEvaluationInputComponents = 128,
            maxTessellationEvaluationOutputComponents = 128,
            maxGeometryShaderInvocations = 127,
            maxGeometryInputComponents = 64,
            maxGeometryOutputComponents = 128,
            maxGeometryOutputVertices = 256,
            maxGeometryTotalOutputComponents = 1024,
            maxFragmentInputComponents = 128,
            maxFragmentOutputAttachments = 8,
            maxFragmentDualSrcAttachments = 1,
            maxFragmentCombinedOutputResources = 8,
            maxComputeSharedMemorySize = 32768,
            maxComputeWorkGroupCount = {65535, 65535, 65535},
            maxComputeWorkGroupInvocations = 1024,
            maxComputeWorkGroupSize = {1024, 1024, 1024},
            subPixelPrecisionBits = 8,
            subTexelPrecisionBits = 8,
            mipmapPrecisionBits = 8,
            maxDrawIndexedIndexValue = 4294967295,
            maxDrawIndirectCount = 4294967295,
            maxSamplerLodBias = 16,
            maxSamplerAnisotropy = 16,
            maxViewports = 16,
            maxViewportDimensions = {16384, 16384},
            viewportBoundsRange = {-32768, 32767},
            viewportSubPixelBits = 8,
            minMemoryMapAlignment = 4096,
            minTexelBufferOffsetAlignment = 4,
            minUniformBufferOffsetAlignment = 4,
            minStorageBufferOffsetAlignment = 4,
            minTexelOffset = -32,
            maxTexelOffset = 31,
            minTexelGatherOffset = -32,
            maxTexelGatherOffset = 31,
            minInterpolationOffset = -2,
            maxInterpolationOffset = 2,
            subPixelInterpolationOffsetBits = 8,
            maxFramebufferWidth = 16384,
            maxFramebufferHeight = 16384,
            maxFramebufferLayers = 1024,
            framebufferColorSampleCounts = 15,
            framebufferDepthSampleCounts = 15,
            framebufferStencilSampleCounts = 15,
            framebufferNoAttachmentsSampleCounts = 15,
            maxColorAttachments = 8,
            sampledImageColorSampleCounts = 15,
            sampledImageIntegerSampleCounts = 15,
            sampledImageDepthSampleCounts = 15,
            sampledImageStencilSampleCounts = 15,
            storageImageSampleCounts = 15,
            maxSampleMaskWords = 1,
            timestampComputeAndGraphics = 1,
            timestampPeriod = 10,
            maxClipDistances = 8,
            maxCullDistances = 8,
            maxCombinedClipAndCullDistances = 8,
            discreteQueuePriorities = 2,
            pointSizeRange = {0, 8192},
            lineWidthRange = {0, 8192},
            pointSizeGranularity = 0.125,
            lineWidthGranularity = 0.125,
            strictLines = 0,
            standardSampleLocations = 1,
            optimalBufferCopyOffsetAlignment = 128,
            optimalBufferCopyRowPitchAlignment = 128,
            nonCoherentAtomSize = 64
          },
          sparseProperties = {
            residencyStandard2DBlockShape = 0,
            residencyStandard2DMultisampleBlockShape = 0,
            residencyStandard3DBlockShape = 0,
            residencyAlignedMipSize = 0,
            residencyNonResidentStrict = 0
          }
        }
        vk = 0x555555a35420
        i = 0
        ctx = 0x555555647f70
        inst = 0x555555a3cf50
        EnumeratePhysicalDevices = 0x7ffff7589fb0 <vkEnumeratePhysicalDevices>
        GetPhysicalDeviceProperties = 0x7ffff7588d20 <vkGetPhysicalDeviceProperties>
        num = 1
        devices = 0x555555a34860
        surf = 0x20000000002
        CreateHeadlessSurfaceEXT = 0x7ffff758d110 <vkCreateHeadlessSurfaceEXT>
        dev = 0x5555556480f0
```

**Comment by Tony-LunarG** [comment]
I know what the problem is.  Fix coming later today
