### ISSUE TITLE
`BUILD.gn` is missing header files

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/Vulkan-ValidationLayers#2810]
**Describe the Issue**
The `BUILD.gn` is missing the following header files:
- `layers/generated/gpu_pre_draw_shader.h`
- `layers/gpu_pre_draw_constants.h`

**Additional context**
This causes ANGLE's presubmit checks to fail, since it verifies the `BUILD.gn` contains all of the necessary files:
https://chromium-review.googlesource.com/c/angle/angle/+/2900288

```
   shared_library //third_party/vulkan-deps/vulkan-validation-layers/src:VkLayer_khronos_validation
 Warning in //third_party/vulkan-deps/vulkan-validation-layers/src:VkLayer_khronos_validation: third_party/vulkan-deps/vulkan-validation-layers/src/layers/gpu_validation.cpp: Invalid include: b'gpu_pre_draw_constants.h'
 Warning in //third_party/vulkan-deps/vulkan-validation-layers/src:VkLayer_khronos_validation: third_party/vulkan-deps/vulkan-validation-layers/src/layers/gpu_validation.cpp: Invalid include: b'gpu_pre_draw_shader.h'
 Traceback (most recent call last):
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 325, in <module>
     libraries = gather_libraries(ROOTS, descs)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 320, in gather_libraries
     dag_traverse(roots, fn)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 114, in dag_traverse
     recurse(x)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 107, in recurse
     recurse(x)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 107, in recurse
     recurse(x)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 107, in recurse
     recurse(x)
   [Previous line repeated 5 more times]
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 99, in recurse
     t = pre_recurse_func(key)
   File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py", line 314, in fn
     assert has_all_includes(target_name, descs), target_name
 AssertionError: //third_party/vulkan-deps/vulkan-validation-layers/src:VkLayer_khronos_validation
```

**Comment by timvpGoogle** [comment]
Pull request is available at: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2811
