### ISSUE TITLE
syncval: assert in dEQP-VK.renderpass.suballocation.formats.r5g6b5_unorm_pack16.input.load.store.clear

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4007]
```
Test case 'dEQP-VK.renderpass.suballocation.formats.r5g6b5_unorm_pack16.input.load.store.clear'..
deqp-vk: /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:3336: void ResourceAccessState::TouchupFirstForLayoutTransition(ResourceUsageTag, const ResourceAccessState::OrderingBarrier&): Assertion `first_accesses_.back().usage_index == SyncStageAccessIndex::SYNC_IMAGE_LAYOUT_TRANSITION' failed.
```
Contents of first_accesses_ is:
```
{{tag = 0, usage_index = SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, ordering_rule = SyncOrdering::kColorAttachment}, 
{tag = 3,  usage_index = SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, ordering_rule = SyncOrdering::kRaster}}

```
Backtrace:

```
#7  0x00007fffd2fbfdf1 in ResourceAccessState::TouchupFirstForLayoutTransition (this=0x55555c872f70, tag=3, layout_ordering=...)
    at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:3336
#8  0x00007fffd2fbf895 in ResourceAccessState::ApplyPendingBarriers (this=0x55555c872f70, tag=3) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:3252
#9  0x00007fffd301b1b1 in ApplyBarrierOpsFunctor<PipelineBarrierOp, std::vector<PipelineBarrierOp, std::allocator<PipelineBarrierOp> > >::operator() (this=0x7fffffffcc80, accesses=0x55555c871598, pos=...)
    at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:1619
#10 0x00007fffd3011bbe in UpdateMemoryAccessState<ApplyBarrierOpsFunctor<PipelineBarrierOp, std::vector<PipelineBarrierOp, std::allocator<PipelineBarrierOp> > > > (accesses=0x55555c871598, range=..., action=...)
    at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:1509
#11 0x00007fffd300450f in UpdateMemoryAccessState<ApplyBarrierOpsFunctor<PipelineBarrierOp, std::vector<PipelineBarrierOp, std::allocator<PipelineBarrierOp> > >, subresource_adapter::ImageRangeGenerator> (
    accesses=0x55555c871598, action=..., range_gen_prebuilt=...) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:1544
#12 0x00007fffd2ff0319 in AccessContext::ApplyUpdateAction<ApplyBarrierOpsFunctor<PipelineBarrierOp, std::vector<PipelineBarrierOp, std::allocator<PipelineBarrierOp> > > > (this=0x55555c871568, view_gen=..., 
    gen_type=AttachmentViewGen::kViewSubresource, action=...) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:1721
#13 0x00007fffd2fbcfae in RenderPassAccessContext::RecordEndRenderPass (this=0x55555c8720e0, external_context=0x55555c871568, tag=3)
    at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:2685
#14 0x00007fffd2fb9dff in CommandBufferAccessContext::RecordEndRenderPass (this=0x55555c8714e0, tag=3) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:2195
#15 0x00007fffd2fd0d32 in SyncOpEndRenderPass::Record (this=0x7fffffffcdd0, cb_context=0x55555c8714e0) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:6434
#16 0x00007fffd2fc3aa2 in SyncValidator::RecordCmdEndRenderPass (this=0x555559abd9b0, commandBuffer=0x55555c8645a0, pSubpassEndInfo=0x0, cmd=CMD_ENDRENDERPASS)
    at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:3927
#17 0x00007fffd2fc3ba0 in SyncValidator::PostCallRecordCmdEndRenderPass (this=0x555559abd9b0, commandBuffer=0x55555c8645a0) at /home/jgebben/src/Vulkan-ValidationLayers/layers/synchronization_validation.cpp:3940
#18 0x00007fffd24e25db in vulkan_layer_chassis::CmdEndRenderPass (commandBuffer=0x55555c8645a0) at /home/jgebben/src/Vulkan-ValidationLayers/layers/generated/chassis.cpp:3742
#19 0x0000555556ac1219 in vkt::(anonymous namespace)::pushRenderPassCommands<vkt::renderpass::RenderpassSubpass1> (vk=..., commandBuffer=0x55555c8645a0, renderPass=..., framebuffer=..., 
    subpassRenderers=std::vector of length 2, capacity 2 = {...}, renderPos=..., renderSize=..., renderPassClearValues=std::vector of length 2, capacity 2 = {...}, 
    render=vkt::(anonymous namespace)::TestConfig::RENDERTYPES_CLEAR) at /home/jgebben/src/VK-GL-CTS/external/vulkancts/modules/vulkan/renderpass/vktRenderPassTests.cpp:2743
#20 0x0000555556ac43ee in vkt::(anonymous namespace)::pushRenderPassCommands (renderingType=<optimized out>, render=vkt::(anonymous namespace)::TestConfig::RENDERTYPES_CLEAR, queueIndex=0, 
    renderPassClearValues=std::vector of length 2, capacity 2 = {...}, renderSize=..., renderPos=..., subpassRenderers=std::vector of length 2, capacity 2 = {...}, framebuffer=..., 
    attachmentResources=std::vector of length 2, capacity 2 = {...}, renderPassInfo=..., renderPass=..., commandBuffer=0x55555c8645a0, vk=...)
    at /home/jgebben/src/VK-GL-CTS/external/vulkancts/modules/vulkan/renderpass/vktRenderPassTests.cpp:3046
#21 vkt::(anonymous namespace)::renderPassTest (context=..., config=...) at /home/jgebben/src/VK-GL-CTS/external/vulkancts/modules/vulkan/renderpass/vktRenderPassTests.cpp:5145
#22 0x0000555556a9d44a in vkt::FunctionInstance1<vkt::(anonymous namespace)::TestConfig>::iterate (this=0x55555c1f57b0)
    at /home/jgebben/src/VK-GL-CTS/external/vulkancts/modules/vulkan/renderpass/../vktTestCaseUtil.hpp:143
#23 0x000055555599ba2e in vkt::TestCaseExecutor::iterate (this=0x555558d1d670) at /home/jgebben/src/VK-GL-CTS/external/vulkancts/modules/vulkan/vktTestPackage.cpp:401
#24 0x0000555557b89bb7 in tcu::TestSessionExecutor::iterateTestCase (this=0x555558d1d3b0, testCase=0x55555c4746c0) at /home/jgebben/src/VK-GL-CTS/framework/common/tcuTestSessionExecutor.cpp:302
#25 0x0000555557b89c43 in tcu::TestSessionExecutor::iterate (this=0x555558d1d3b0) at /home/jgebben/src/VK-GL-CTS/framework/common/tcuTestSessionExecutor.cpp:139
#26 0x0000555557b5f5c9 in tcu::App::iterate (this=this@entry=0x555558d1c3d0) at /home/jgebben/src/VK-GL-CTS/framework/common/tcuApp.cpp:221
#27 0x00005555559868b8 in main (argc=<optimized out>, argv=<optimized out>) at /home/jgebben/src/VK-GL-CTS/framework/platform/tcuMain.cpp:58

```

**Comment by Tony-LunarG** [comment]
This no longer crashes for me with today's master VVL and CTS 1.3.3.1
