### ISSUE TITLE
Assert when using variable descriptor count without setting all descriptors

### ISSUE THREAD

**Issue by martin-ejdestig** [KhronosGroup/Vulkan-ValidationLayers#4239]
**Describe the Issue**

(Originally encountered this in non public Vulkan 1.2 code from which it is not easy to extract a minimal example. So using Sascha Willems's `VK_EXT_descriptor_indexing` example instead where it is easy to trigger the same problem.)

Changing https://github.com/SaschaWillems/Vulkan/blob/master/examples/descriptorindexing/descriptorindexing.cpp to set an upper bound on the unsized array +1 larger than what is needed like so:

```
diff --git a/examples/descriptorindexing/descriptorindexing.cpp b/examples/descriptorindexing/descriptorindexing.cpp
index 354d3b55..56f7aac5 100644
--- a/examples/descriptorindexing/descriptorindexing.cpp
+++ b/examples/descriptorindexing/descriptorindexing.cpp
@@ -200,7 +200,7 @@ public:
                // Descriptor pool
                std::vector<VkDescriptorPoolSize> poolSizes = {
                        vks::initializers::descriptorPoolSize(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1),
-                       vks::initializers::descriptorPoolSize(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, static_cast<uint32_t>(textures.size()))
+                       vks::initializers::descriptorPoolSize(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, static_cast<uint32_t>(textures.size() + 1))
                };
                VkDescriptorPoolCreateInfo descriptorPoolInfo = vks::initializers::descriptorPoolCreateInfo(poolSizes, 2);
                VK_CHECK_RESULT(vkCreateDescriptorPool(device, &descriptorPoolInfo, nullptr, &descriptorPool));
@@ -212,7 +212,7 @@ public:
                        // [POI] Binding 1 contains a texture array that is dynamically non-uniform sampled from
                        // In the fragment shader:
                        //      outFragColor = texture(textures[nonuniformEXT(inTexIndex)], inUV);
-                       vks::initializers::descriptorSetLayoutBinding(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT, 1, static_cast<uint32_t>(textures.size()))
+                       vks::initializers::descriptorSetLayoutBinding(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT, 1, static_cast<uint32_t>(textures.size() + 1))
                };
 
                // [POI] The fragment shader will be using an unsized array of samplers, which has to be marked with the VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT
```

And then running the example with `descriptorindexing --validation` (`--validation` to enable `VK_LAYER_KHRONOS_validation`) results in an assert that aborts the application:

```
/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter>; _Alloc = std::allocator<std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter> >; reference = std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

Backtrace:

```
#0  0x00007ffff788e36c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff783e838 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7828535 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7cd2002 in std::__glibcxx_assert_fail (file=file@entry=0x7ffff4101678 "/usr/include/c++/12.1.0/bits/stl_vector.h", line=line@entry=1123, 
    function=function@entry=0x7ffff42f9a38 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter>; _Alloc "..., 
    condition=condition@entry=0x7ffff426db7f "__n < this->size()") at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x00007ffff40daf51 in std::vector<std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter>, std::allocator<std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter> > >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/12.1.0/bits/stl_vector.h:1123
#5  std::vector<std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter>, std::allocator<std::unique_ptr<cvdescriptorset::Descriptor, cvdescriptorset::DescriptorSet::DescriptorDeleter> > >::operator[] (
    this=<optimized out>, __n=<optimized out>) at /usr/include/c++/12.1.0/bits/stl_vector.h:1121
#6  cvdescriptorset::DescriptorSet::UpdateDrawState(ValidationStateTracker*, CMD_BUFFER_STATE*, CMD_TYPE, PIPELINE_STATE const*, std::map<unsigned int, DescriptorRequirement, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, DescriptorRequirement> > > const&) [clone .constprop.0] (this=this@entry=0x555555fe8d30, device_data=0x5555560db180, cb_node=cb_node@entry=0x555556414570, cmd_type=cmd_type@entry=CMD_DRAWINDEXED, binding_req_map=std::map with 2 elements = {...}, pipe=<optimized out>)
    at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-sdk-1.3.216.0/layers/descriptor_sets.cpp:661
#7  0x00007ffff3d231d9 in CMD_BUFFER_STATE::UpdateDrawState (this=0x555556414570, cmd_type=<optimized out>, bind_point=<optimized out>) at /usr/include/c++/12.1.0/bits/shared_ptr_base.h:1665
#8  0x00007ffff40d9f3f in CMD_BUFFER_STATE::UpdateStateCmdDrawDispatchType (bind_point=VK_PIPELINE_BIND_POINT_GRAPHICS, cmd_type=CMD_DRAWINDEXED, this=0x555556414570)
    at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-sdk-1.3.216.0/layers/cmd_buffer_state.cpp:963
#9  CMD_BUFFER_STATE::UpdateStateCmdDrawType(CMD_TYPE, VkPipelineBindPoint) [clone .constprop.0] (this=0x555556414570, cmd_type=cmd_type@entry=CMD_DRAWINDEXED, bind_point=VK_PIPELINE_BIND_POINT_GRAPHICS)
    at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-sdk-1.3.216.0/layers/cmd_buffer_state.cpp:969
#10 0x00007ffff3c5f959 in ValidationStateTracker::PostCallRecordCmdDrawIndexed (this=<optimized out>, commandBuffer=<optimized out>, indexCount=<optimized out>, instanceCount=<optimized out>, firstIndex=<optimized out>, vertexOffset=<optimized out>, 
    firstInstance=0) at /usr/include/c++/12.1.0/bits/shared_ptr_base.h:1665
#11 0x00007ffff3ba3f8d in vulkan_layer_chassis::CmdDrawIndexed (commandBuffer=0x55555640e110, indexCount=216, instanceCount=1, firstIndex=0, vertexOffset=0, firstInstance=0)
    at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-sdk-1.3.216.0/layers/generated/chassis.cpp:3065
#12 0x00005555555c39fd in VulkanExample::buildCommandBuffers() ()
#13 0x00005555555c3e1f in VulkanExample::prepare() ()
#14 0x00005555555bf00c in main ()
```

Fixing the example, which also makes the assert in the validation layer go away, can be done by just setting `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT`:

```
diff --git a/examples/descriptorindexing/descriptorindexing.cpp b/examples/descriptorindexing/descriptorindexing.cpp
index 56f7aac5..49d5774a 100644
--- a/examples/descriptorindexing/descriptorindexing.cpp
+++ b/examples/descriptorindexing/descriptorindexing.cpp
@@ -63,6 +63,7 @@ public:
                physicalDeviceDescriptorIndexingFeatures.shaderSampledImageArrayNonUniformIndexing = VK_TRUE;
                physicalDeviceDescriptorIndexingFeatures.runtimeDescriptorArray = VK_TRUE;
                physicalDeviceDescriptorIndexingFeatures.descriptorBindingVariableDescriptorCount = VK_TRUE;
+               physicalDeviceDescriptorIndexingFeatures.descriptorBindingPartiallyBound = VK_TRUE;
 
                deviceCreatepNextChain = &physicalDeviceDescriptorIndexingFeatures;
        }
@@ -223,7 +224,7 @@ public:
                setLayoutBindingFlags.bindingCount = 2;
                std::vector<VkDescriptorBindingFlagsEXT> descriptorBindingFlags = {
                        0,
-                       VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT
+                       VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT | VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT
                };
                setLayoutBindingFlags.pBindingFlags = descriptorBindingFlags.data();
```

But it is not good to have the application abort() when `VK_LAYER_KHRONOS_validation` is enabled and also not being told what the problem is.

**Environment:**
 - OS: Linux
 - GPU: GeForce GTX 970
 - SDK or header version if building from repo: 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): ?

**Comment by jeremyg-lunarg** [comment]
The assert will get inadvertently fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4126. But it seems like there should be some sort of valid usage error in this case, which I need to find in the spec.

**Comment by jeremyg-lunarg** [comment]
The section about [Descriptor Sets](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-sets) says:
```
For descriptor set bindings created without the VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT bit set, all descriptors in that binding that are statically used must have been populated before the descriptor set is [consumed](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-binding).
```

However, the only VUID even close to the above is:
```
VUID-vkCmdDraw-None-02699
Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command
```
But that doesn't get checked until after the assert.

**Comment by jeremyg-lunarg** [comment]
#4126 is merged, so this should be fixed. Please reopen if you're still seeing it.
