### ISSUE TITLE
vkCreateImage with VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT

### ISSUE THREAD

**Issue by szihs** [KhronosGroup/Vulkan-ValidationLayers#456]
Hello,

When enabling "core_validaton" layer, vkCreateImage is not properly dealt when tiling is DRM_FORMAT_MODIFIER_EXT,

As per current code, it calls vkGetPhysicalDeviceImageFormatProperties (), from the below backtrace.

where-ever spec says it should call vkGetPhysicalDeviceImageFormatProperties2() instead.

```
#6  0xb343ba8c in core_validation::GetImageFormatProperties(core_validation::layer_data*, VkImageCreateInfo const*, VkImageFormatProperties*) ()
   from /usr/lib/libVkLayer_core_validation.so
#7  0xb3485214 in PreCallValidateCreateImage(core_validation::layer_data*, VkImageCreateInfo const*, VkAllocationCallbacks const*, unsigned long long*) ()
   from /usr/lib/libVkLayer_core_validation.so
#8  0xb3440a10 in core_validation::CreateImage(VkDevice_T*, VkImageCreateInfo const*, VkAllocationCallbacks const*, unsigned long long*) ()
   from /usr/lib/libVkLayer_core_validation.so
#9  0xb32070b8 in object_tracker::CreateImage(VkDevice_T*, VkImageCreateInfo con---Type <return> to continue, or q <return> to quit---
st*, VkAllocationCallbacks const*, unsigned long long*) ()
   from /usr/lib/libVkLayer_object_tracker.so
#10 0xb2f92db2 in parameter_validation::vkCreateImage(VkDevice_T*, VkImageCreateInfo const*, VkAllocationCallbacks const*, unsigned long long*) ()
   from /usr/lib/libVkLayer_parameter_validation.so
```

Kindly check!
Refer:
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkGetPhysicalDeviceImageFormatProperties.html
tiling must not be VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT. (Use vkGetPhysicalDeviceImageFormatProperties2 instead).

Regards,
Harsh

**Comment by mark-lunarg** [comment]
In work.
