### ISSUE TITLE
formatting.yml breaks on sdk-* branches

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5164]
Doesn't work on sdk-* branches:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/3988774339/jobs/6867751208

<details>
<summary>sdk-1.3.29 CI failure</summary>

```sh
Run python3 scripts/check_code_format.py --fetch-main --target-refspec=FETCH_HEAD
fatal: couldn't find remote ref master
Fetching master branch...
Traceback (most recent call last):
  File "scripts/check_code_format.py", line 315, in <module>
    main()
  File "scripts/check_code_format.py", line 262, in main
    subprocess.check_call(['git', 'fetch', 'https://github.com/KhronosGroup/Vulkan-ValidationLayers.git', 'master'])
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'fetch', 'https://github.com/KhronosGroup/Vulkan-ValidationLayers.git', 'master']' returned non-zero exit status 128.
```

</detail>

**Comment by juan-lunarg** [comment]
Looks this has been addressed:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/tmp-1.3.241
