### ISSUE TITLE
GPL validation has regressed

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#5609]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5233 is broken again as of dbcdcc1260e5b1a524c8c5ba8cb2859e0cdc60f4

**Comment by zmike** [comment]
Backtrace from creating a GPL lib with only fragment shader stage:

```
#0  0x97817e57 in CoreChecks::ValidateFsOutputsAgainstDynamicRenderingRenderPass (this=0xcb6a680, module_state=..., entrypoint=..., pipeline=...)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/core_checks/shader_validation.cpp:156
#1  0x9782b1cd in CoreChecks::ValidateGraphicsPipelineShaderState (this=0xcb6a680, pipeline=...)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/core_checks/shader_validation.cpp:3166
#2  0x9775d686 in CoreChecks::ValidatePipeline (this=0xcb6a680, pipeline=...)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/core_checks/pipeline_validation.cpp:227
#3  0x97762462 in CoreChecks::PreCallValidateCreateGraphicsPipelines (this=0xcb6a680, device=0xc8c78d8, pipelineCache=0, count=1, pCreateInfos=0x91a3d580, 
    pAllocator=0x0, pPipelines=0x91a3d4b8, cgpl_state_data=0x91a3d350)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/core_checks/pipeline_validation.cpp:943
#4  0x9797977c in vulkan_layer_chassis::CreateGraphicsPipelines (device=0xc8c78d8, pipelineCache=0, createInfoCount=1, pCreateInfos=0x91a3d580, 
    pAllocator=0x0, pPipelines=0x91a3d4b8) at /home/zmike/src/Vulkan-ValidationLayers/layers/generated/chassis.cpp:598
#5  0xa3c4992d in create_gfx_pipeline_library (screen=0xc0bde68, objs=0x91a3d86c, layout=18371126261020885152, pipeline_cache=0)
    at ../src/gallium/drivers/zink/zink_pipeline.c:773
#6  0xa3c499f1 in zink_create_gfx_pipeline_separate (screen=0xc0bde68, objs=0x91a3d86c, layout=18371126261020885152)
    at ../src/gallium/drivers/zink/zink_pipeline.c:790
#7  0xa3c57742 in precompile_separate_shader_job (data=0x8d15a078, gdata=0xc0bde68, thread_index=0) at ../src/gallium/drivers/zink/zink_program.c:2056
#8  0xa2c5533d in util_queue_thread_func (input=0xc025bc0) at ../src/util/u_queue.c:309
#9  0xa2cb6f85 in impl_thrd_routine (p=0xcba3210) at ../src/c11/impl/threads_posix.c:67
#10 0xf09d099d in start_thread () from /lib/libc.so.6
#11 0xf0a5a48c in clone3 () from /lib/libc.so.6
```

**Comment by zmike** [comment]
Here too

```
#0  0x00007ffff7b5588d in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007fffea475af5 in safe_VkPipelineRenderingCreateInfo::safe_VkPipelineRenderingCreateInfo (this=0x7fffc402b840, in_struct=0x7fffceffc9f0)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/generated/vk_safe_struct.cpp:19876
#2  0x00007fffea6d46cc in RENDER_PASS_STATE::RENDER_PASS_STATE (this=0x7fffc402b750, pPipelineRenderingCreateInfo=0x7fffceffc9f0)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/state_tracker/render_pass_state.cpp:301
#3  0x00007fffea79e1d5 in std::_Construct<RENDER_PASS_STATE, VkPipelineRenderingCreateInfo const*&> (__p=0x7fffc402b750)
    at /usr/include/c++/12/bits/stl_construct.h:119
#4  0x00007fffea7922b4 in std::allocator_traits<std::allocator<void> >::construct<RENDER_PASS_STATE, VkPipelineRenderingCreateInfo const*&> (
    __p=0x7fffc402b750) at /usr/include/c++/12/bits/alloc_traits.h:635
#5  0x00007fffea7824cd in std::_Sp_counted_ptr_inplace<RENDER_PASS_STATE, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<VkPipelineRenderingCreateInfo const*&> (this=0x7fffc402b740, __a=...) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#6  0x00007fffea770eee in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<RENDER_PASS_STATE, std::allocator<void>, VkPipelineRenderingCreateInfo const*&> (this=0x7fffceffbee8, __p=@0x7fffceffbee0: 0x0, __a=...) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#7  0x00007fffea762904 in std::__shared_ptr<RENDER_PASS_STATE, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, VkPipelineRenderingCreateInfo const*&> (this=0x7fffceffbee0, __tag=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#8  0x00007fffea75505f in std::shared_ptr<RENDER_PASS_STATE>::shared_ptr<std::allocator<void>, VkPipelineRenderingCreateInfo const*&> (this=0x7fffceffbee0, 
    __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#9  0x00007fffea7488b8 in std::make_shared<RENDER_PASS_STATE, VkPipelineRenderingCreateInfo const*&> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#10 0x00007fffea71f431 in ValidationStateTracker::PreCallValidateCreateGraphicsPipelines (this=0x46f5400, device=0x46067e0, pipelineCache=0x130160000000005c, 
    count=1, pCreateInfos=0x7fffceffc740, pAllocator=0x0, pPipelines=0x7fffceffc608, cgpl_state_data=0x7fffceffc3a0)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/state_tracker/state_tracker.cpp:2400
#11 0x00007fffe9d1c834 in CoreChecks::PreCallValidateCreateGraphicsPipelines (this=0x46f5400, device=0x46067e0, pipelineCache=0x130160000000005c, count=1, 
    pCreateInfos=0x7fffceffc740, pAllocator=0x0, pPipelines=0x7fffceffc608, cgpl_state_data=0x7fffceffc3a0)
    at /home/zmike/src/Vulkan-ValidationLayers/layers/core_checks/pipeline_validation.cpp:938
#12 0x00007fffe9f078df in vulkan_layer_chassis::CreateGraphicsPipelines (device=0x46067e0, pipelineCache=0x130160000000005c, createInfoCount=1, 
    pCreateInfos=0x7fffceffc740, pAllocator=0x0, pPipelines=0x7fffceffc608) at /home/zmike/src/Vulkan-ValidationLayers/layers/generated/chassis.cpp:598
#13 0x00007ffff6c2dc7d in create_gfx_pipeline_library (screen=0x39250a0, objs=0x7fffbc00a138, layout=0x612f93000000004e, pipeline_cache=0x130160000000005c)
    at ../src/gallium/drivers/zink/zink_pipeline.c:773
#14 0x00007ffff6c2dcf2 in zink_create_gfx_pipeline_library (screen=0x39250a0, prog=0x7fffbc009fa0) at ../src/gallium/drivers/zink/zink_pipeline.c:784
#15 0x00007ffff6c3c8f7 in zink_create_pipeline_lib (screen=0x39250a0, prog=0x7fffbc009fa0, state=0x7fffceffcad0)
    at ../src/gallium/drivers/zink/zink_program.c:1940
#16 0x00007ffff6c3cf8f in precompile_job (data=0x7fffbc009fa0, gdata=0x39250a0, thread_index=0) at ../src/gallium/drivers/zink/zink_program.c:2040
#17 0x00007ffff5a949bc in util_queue_thread_func (input=0x458e9e0) at ../src/util/u_queue.c:309
#18 0x00007ffff5afda2a in impl_thrd_routine (p=0x458ea00) at ../src/c11/impl/threads_posix.c:67
#19 0x00007ffff7a8e12d in start_thread () from /lib64/libc.so.6
#20 0x00007ffff7b0fbc0 in clone3 () from /lib64/libc.so.6
```

**Comment by juan-lunarg** [comment]
Looks like this regressed due to lack of testing. When this is fixed we will want to add a test to prevent a regression.

**Comment by spencer-lunarg** [comment]
@zmike if you are seeing the issue still please just reopen again with details
