### ISSUE TITLE
Crash in ARM bestpractice

### ISSUE THREAD

**Issue by djdeath** [KhronosGroup/Vulkan-ValidationLayers#6963]
**Environment:**
 - OS: Linux Ubuntu 22.04
 - GPU and driver version: Intel/Mesa main branch
 - SDK or header version if building from repo: a766b0cae98add5cc13b510c50bd76309c220a29
 - Options enabled (synchronization, best practices, etc.): best pratices

**Describe the Issue**

Running into a crash while running with Zink on top of Intel/Mesa using the following dEQP test : 

```
./deqp-gles31  -n dEQP-GLES31.functional.shaders.helper_invocation.derivate.lines_max_samples_dfdx
```

The `rp_state` pointer is NULL.

```
Thread 1 "deqp-gles31" received signal SIGSEGV, Segmentation fault.
BestPractices::ValidateMultisampledBlendingArm (this=0x5555574b5640, createInfoCount=1, pCreateInfos=0x7fffffffb000, create_info_loc=...) at Vulkan-ValidationLayers/layers/best_practices/bp_pipeline.cpp:55
55	        const auto& subpass = rp_state->createInfo.pSubpasses[create_info->subpass];
(gdb) bt
#0  BestPractices::ValidateMultisampledBlendingArm (this=0x5555574b5640, createInfoCount=1, pCreateInfos=0x7fffffffb000, create_info_loc=...)
    at Vulkan-ValidationLayers/layers/best_practices/bp_pipeline.cpp:55
#1  0x00007fffe4949a38 in BestPractices::PreCallValidateCreateGraphicsPipelines (this=0x5555574b5640, device=0x555557499c10, pipelineCache=0x0, createInfoCount=1, pCreateInfos=0x7fffffffb000, pAllocator=0x0, 
    pPipelines=0x7fffffffaf88, error_obj=..., cgpl_state_data=0x7fffffffade0) at Vulkan-ValidationLayers/layers/best_practices/bp_pipeline.cpp:140
#2  0x00007fffe534a6f6 in vulkan_layer_chassis::CreateGraphicsPipelines (device=0x555557499c10, pipelineCache=0x0, createInfoCount=1, pCreateInfos=0x7fffffffb000, pAllocator=0x0, pPipelines=0x7fffffffaf88)
    at Vulkan-ValidationLayers/layers/vulkan/generated/chassis.cpp:662
#3  0x00007ffff555b1ff in zink_create_gfx_pipeline_output (screen=0x5555564b1c60, state=0x555556430060) at ../src/gallium/drivers/zink/zink_pipeline.c:626
#4  0x00007ffff555c9e2 in zink_find_or_create_output (ctx=0x55555642bd60) at ../src/gallium/drivers/zink/zink_pipeline.c:976
#5  0x00007ffff555506e in zink_get_gfx_pipeline<(zink_dynamic_state)5, true> (ctx=0x55555642bd60, prog=0x555557d3e9b0, state=0x555556430060, mode=MESA_PRIM_LINES)
    at ../src/gallium/drivers/zink/zink_program_state.hpp:212
#6  0x00007ffff554fa07 in update_gfx_pipeline<(zink_dynamic_state)5, true> (ctx=0x55555642bd60, bs=0x5555575ac1e0, mode=MESA_PRIM_LINES, can_dgc=false) at ../src/gallium/drivers/zink/zink_draw.cpp:407
#7  0x00007ffff554356b in zink_draw<(zink_multidraw)1, (zink_dynamic_state)5, true, false> (pctx=0x55555642bd60, dinfo=0x5555575ee3f8, drawid_offset=0, dindirect=0x0, draws=0x7fffffffb884, num_draws=1, 
    vstate=0x0, partial_velem_mask=0) at ../src/gallium/drivers/zink/zink_draw.cpp:682
#8  0x00007ffff54698f5 in zink_draw_vbo<(zink_multidraw)1, (zink_dynamic_state)5, true> (pctx=0x55555642bd60, info=0x5555575ee3f8, drawid_offset=0, indirect=0x0, draws=0x7fffffffb884, num_draws=1)
    at ../src/gallium/drivers/zink/zink_draw.cpp:1135
#9  0x00007ffff51ee832 in tc_call_draw_single (pipe=0x55555642bd60, call=0x5555575ee3f0, last_ptr=0x5555575ee520) at ../src/gallium/auxiliary/util/u_threaded_context.c:3834
#10 0x00007ffff51e480e in batch_execute (parsing=false, last=0x5555575ee520, pipe=0x55555642bd60, batch=0x5555575ee1a0) at ../src/gallium/auxiliary/util/u_threaded_context.c:461
#11 tc_batch_execute (job=0x5555575ee1a0, gdata=0x0, thread_index=0) at ../src/gallium/auxiliary/util/u_threaded_context.c:512
#12 0x00007ffff51e5209 in _tc_sync (tc=0x5555575ec0e0, info=0x7ffff6bd5996 "texture", func=0x7ffff6bd6018 <__func__.39> "tc_texture_map") at ../src/gallium/auxiliary/util/u_threaded_context.c:750
#13 0x00007ffff51ebbb6 in tc_texture_map (_pipe=0x5555575ec0e0, resource=0x555557d30bc0, level=0, usage=1, box=0x7fffffffc940, transfer=0x555557d30b60) at ../src/gallium/auxiliary/util/u_threaded_context.c:2798
#14 0x00007ffff47f5ed3 in pipe_texture_map (context=0x5555575ec0e0, resource=0x555557d30bc0, level=0, layer=0, access=1, x=0, y=0, w=256, h=256, transfer=0x555557d30b60)
    at ../src/gallium/auxiliary/util/u_inlines.h:557
#15 0x00007ffff47f6d74 in _mesa_map_renderbuffer (ctx=0x7fffe0390010, rb=0x555557d30af0, x=0, y=0, w=256, h=256, mode=1, mapOut=0x7fffffffca70, rowStrideOut=0x7fffffffca5c, flip_y=false)
    at ../src/mesa/main/renderbuffer.c:495
#16 0x00007ffff4ce841a in readpixels_memcpy (ctx=0x7fffe0390010, x=0, y=0, width=256, height=256, format=6408, type=5121, pixels=0x7fffe034f010, packing=0x7fffffffcc60) at ../src/mesa/main/readpix.c:260
#17 0x00007ffff4ce9c40 in _mesa_readpixels (ctx=0x7fffe0390010, x=0, y=0, width=256, height=256, format=6408, type=5121, packing=0x7fffffffcc60, pixels=0x7fffe034f010) at ../src/mesa/main/readpix.c:898
#18 0x00007ffff4d603ed in st_ReadPixels (ctx=0x7fffe0390010, x=0, y=0, width=256, height=256, format=6408, type=5121, pack=0x7fffffffcc60, pixels=0x7fffe034f010)
    at ../src/mesa/state_tracker/st_cb_readpixels.c:568
#19 0x00007ffff4ceaf64 in read_pixels (no_error=false, pixels=0x7fffe034f010, bufSize=2147483647, type=5121, format=6408, height=256, width=256, y=0, x=0) at ../src/mesa/main/readpix.c:1199
#20 _mesa_ReadnPixelsARB (x=0, y=0, width=256, height=256, format=6408, type=5121, bufSize=2147483647, pixels=0x7fffe034f010) at ../src/mesa/main/readpix.c:1216
#21 0x00007ffff4ceb01d in _mesa_ReadPixels (x=0, y=0, width=256, height=256, format=6408, type=5121, pixels=0x7fffe034f010) at ../src/mesa/main/readpix.c:1231
#22 0x00007ffff49feecc in _mesa_marshal_ReadPixels (x=0, y=0, width=256, height=256, format=6408, type=5121, pixels=0x7fffe034f010) at src/mapi/glapi/gen/marshal_generated1.c:1717
#23 0x0000555555e0e1db in glu::readPixels (context=..., x=0, y=0, dst=...) at vulkancts/framework/opengl/gluPixelTransfer.cpp:61
#24 0x0000555555a4589a in deqp::gles31::Functional::(anonymous namespace)::FboHelper::readPixels (this=0x555557d2dbd0, x=0, y=0, dst=...)
    at vulkancts/modules/gles31/functional/es31fShaderHelperInvocationTests.cpp:280
#25 0x0000555555a483db in deqp::gles31::Functional::(anonymous namespace)::HelperInvocationDerivateCase::iterate (this=0x5555576b2980)
    at vulkancts/modules/gles31/functional/es31fShaderHelperInvocationTests.cpp:638
#26 0x000055555561825c in deqp::gles31::TestCaseWrapper<deqp::gles31::TestPackage>::iterate (this=0x555556400ba0, testCase=0x5555576b2980)
    at vulkancts/modules/gles31/tes31TestCaseWrapper.hpp:86
#27 0x0000555555fb1412 in tcu::TestSessionExecutor::iterateTestCase (this=0x555556400930, testCase=0x5555576b2980) at vulkancts/framework/common/tcuTestSessionExecutor.cpp:334
#28 0x0000555555fafe5a in tcu::TestSessionExecutor::iterate (this=0x555556400930) at vulkancts/framework/common/tcuTestSessionExecutor.cpp:139
#29 0x0000555555f6e688 in tcu::App::iterate (this=0x5555563fee40) at vulkancts/framework/common/tcuApp.cpp:224
#30 0x00005555556080b9 in main (argc=3, argv=0x7fffffffd4c8) at vulkancts/framework/platform/tcuMain.cpp:58

````

**Expected behavior**

No crash

**Valid Usage ID**

**Additional context**

**Comment by spencer-lunarg** [comment]
@djdeath I wish we had better testing for best practice like we do for validation... I plan to do a run of our normal CI flow with BP turned on to at least make sure we don't just like crash like this... in the short term, should have solve the null renderpass issue
