### ISSUE TITLE
SyncVal: complains about missing image barrier SYNC-HAZARD-READ-AFTER-WRITE appears not taking account of global memory barrier

### ISSUE THREAD

**Issue by cclao** [KhronosGroup/Vulkan-ValidationLayers#7819]
**Environment:**
 - OS: linux
 - GPU and driver version:   SwiftShader
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):
This is reproduced with ANGLE.

**Describe the Issue**

To reproduce:
Make sure this CL is in ANGLE
https://chromium-review.googlesource.com/c/angle/angle/+/5437095

And then remove the SyncVal supression in `src/libANGLE/renderer/vulkan/vk_renderer.cpp` file

Build ANGLE's end2end test:
```
autoninja -C out/LinuxDebug angle_end2end_tests
```

Note: here is my LinuxDebug gn args:
```
target_cpu = "x64"
is_debug = true
is_clang = true
dcheck_always_on = true
build_angle_deqp_tests = true
build_angle_trace_perf_tests=true
angle_enable_vulkan_validation_layers = true
treat_warnings_as_errors = false
```

And then run the test
```
cd out/LinuxDebug
gdb ./angle_end2end_tests
(gdb) r --use-angle=swiftshader --gtest_filter=Texture2DTest.UploadThenFSThenNewRPThenVS/ES2_Vulkan           
```

And you will see this error

```
../../src/tests/test_utils/ANGLETest.cpp:65: Failure
vk_renderer.cpp:829 (DebugUtilsMessenger): [ SYNC-HAZARD-READ-AFTER-WRITE ] Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x300000000030, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xe4d96472 | vkCmdDraw():  Hazard READ_AFTER_WRITE for VkImageView 0x300000000030[], in VkCommandBuffer 0x55555abc03b0[], and VkPipeline 0x3c000000003c[], VkDescriptorSet 0x400000000040[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 0. Access info (usage: SYNC_VERTEX_SHADER_SHADER_SAMPLED_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_SHADER_BINDING_TABLE_READ|SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, command: vkCmdPipelineBarrier, seq_no: 3, VkImage 0x2f000000002f[], VkImage 0x2c000000002c[], reset_no: 1).
                            Object: 0x300000000030 (type = Image View(14))
```

Here is what I have seen in gdb
1) First we create VkImage and upload the data. VkImage is `0x2f000000002f`, and now it is in VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
2) Render pass starts and image is sampled by fragment shader. We issued a VkPipelineBarrier to change layout from VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL

```
Thread 1 "angle_end2end_t" hit Breakpoint 2, rx::vk::priv::CommandBuffer::pipelineBarrier (this=0x55555a72dc00, srcStageMask=4097, dstStageMask=1152, dependencyFlags=0, 
    memoryBarrierCount=0, memoryBarriers=0x7fffffffac98, bufferMemoryBarrierCount=0, bufferMemoryBarriers=0x0, imageMemoryBarrierCount=2, imageMemoryBarriers=0x55555ad20810)
    at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:809
809	    ASSERT(valid());
810	    vkCmdPipelineBarrier(mHandle, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount,
811	                         memoryBarriers, bufferMemoryBarrierCount, bufferMemoryBarriers,
812	                         imageMemoryBarrierCount, imageMemoryBarriers);

(gdb) bt
#0  rx::vk::priv::CommandBuffer::pipelineBarrier (this=0x55555a72dc00, srcStageMask=4097, dstStageMask=1152, dependencyFlags=0, memoryBarrierCount=0, memoryBarriers=0x7fffffffac98, 
    bufferMemoryBarrierCount=0, bufferMemoryBarriers=0x0, imageMemoryBarrierCount=2, imageMemoryBarriers=0x55555ad20810) at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:809
#1  0x00007ffff687987b in rx::vk::PipelineBarrier::execute (this=0x55555ac2aef8, primary=0x55555a72dc00) at ../../src/libANGLE/renderer/vulkan/vk_helpers.h:680
#2  0x00007ffff6838114 in rx::vk::CommandBufferHelperCommon::executeBarriers (this=0x55555ac2ad00, features=..., commandsState=0x55555a72dbd0)
    at ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp:1668
#3  0x00007ffff6841162 in rx::vk::RenderPassCommandBufferHelper::flushToPrimary (this=0x55555ac2ad00, context=0x55555abfc748, commandsState=0x55555a72dbd0, renderPass=..., 
    framebufferOverride=0x0) at ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp:2833
#4  0x00007ffff65bc0c6 in rx::vk::CommandQueue::flushRenderPassCommands (this=0x55555a72da70, context=0x55555abfc748, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfe900) at ../../src/libANGLE/renderer/vulkan/CommandProcessor.cpp:1357
#5  0x00007ffff68ce118 in rx::vk::Renderer::flushRenderPassCommands (this=0x55555a722e90, context=0x55555abfc748, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfe900) at ../../src/libANGLE/renderer/vulkan/vk_renderer.cpp:5730
#6  0x00007ffff65ffe61 in rx::ContextVk::flushCommandsAndEndRenderPassWithoutSubmit (this=0x55555abfc720, reason=rx::RenderPassClosureReason::AlreadySpecifiedElsewhere)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:8011
#7  0x00007ffff65e89d2 in rx::ContextVk::flushCommandsAndEndRenderPass (this=0x55555abfc720, reason=rx::RenderPassClosureReason::AlreadySpecifiedElsewhere)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:8042
#8  0x00007ffff65ea315 in rx::ContextVk::flushDirtyGraphicsRenderPass (this=0x55555abfc720, dirtyBitsIterator=0x7fffffffc4e0, dirtyBitMask=..., 
    reason=rx::RenderPassClosureReason::AlreadySpecifiedElsewhere) at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:8062
#9  0x00007ffff65dcc85 in rx::ContextVk::handleDirtyGraphicsRenderPass (this=0x55555abfc720, dirtyBitsIterator=0x7fffffffc4e0, dirtyBitMask=...)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:2390
#10 0x00007ffff65e7990 in rx::ContextVk::setupDraw (this=0x55555abfc720, context=0x55555abf8060, mode=gl::PrimitiveMode::Triangles, firstVertexOrInvalid=0, vertexOrIndexCount=6, 
    instanceCount=1, indexTypeOrInvalid=gl::DrawElementsType::InvalidEnum, indices=0x0, dirtyBitMask=...) at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:1593
#11 0x00007ffff65eeebc in rx::ContextVk::drawArrays (this=0x55555abfc720, context=0x55555abf8060, mode=gl::PrimitiveMode::Triangles, first=0, count=6)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:4053
#12 0x00007ffff6518e16 in gl::Context::drawArrays (this=0x55555abf8060, mode=gl::PrimitiveMode::Triangles, first=0, count=6) at ../../src/libANGLE/Context.inl.h:152
#13 0x00007ffff65062c7 in GL_DrawArrays (mode=4, first=0, count=6) at ../../src/libGLESv2/entry_points_gles_2_0_autogen.cpp:1260
#14 0x0000555557d3c854 in ANGLETestBase::drawQuad (this=0x55555a71af30, program=1, positionAttribName=..., positionAttribZ=0.5, positionAttribXYScale=1, useVertexBuffer=false, 
    useInstancedDrawCalls=false, useTessellationPatches=false, numInstances=0) at ../../src/tests/test_utils/ANGLETest.cpp:1045
#15 0x0000555557d3c4a3 in ANGLETestBase::drawQuad (this=0x55555a71af30, program=1, positionAttribName=..., positionAttribZ=0.5, positionAttribXYScale=1, useVertexBuffer=false)
    at ../../src/tests/test_utils/ANGLETest.cpp:963
#16 0x0000555557d3c449 in ANGLETestBase::drawQuad (this=0x55555a71af30, program=1, positionAttribName=..., positionAttribZ=0.5, positionAttribXYScale=1)
    at ../../src/tests/test_utils/ANGLETest.cpp:954
#17 0x0000555557d3c405 in ANGLETestBase::drawQuad (this=0x55555a71af30, program=1, positionAttribName=..., positionAttribZ=0.5) at ../../src/tests/test_utils/ANGLETest.cpp:945

(gdb) p imageMemoryBarriers[0]            
$1 = {
  sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
  pNext = 0x0,
  srcAccessMask = 4096,
  dstAccessMask = 32,
  oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
  newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
  srcQueueFamilyIndex = 0,
  dstQueueFamilyIndex = 0,
  image = 0x2f000000002f,
  subresourceRange = {
    aspectMask = 1,
    baseMipLevel = 0,
    levelCount = 1,
    baseArrayLayer = 0,
    layerCount = 1
  }
}
```

here: 
```
srcStageMask is 4097 == 0x1001 == VK_PIPELINE_STAGE_TRANSFER_BIT | VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
dstStageMask is 1152 == 0x480 == VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT
```

And then we start the render pass and end render pass.

```
(gdb) c
Continuing.

Thread 1 "angle_end2end_t" hit Breakpoint 4, rx::vk::priv::CommandBuffer::beginRenderPass (this=0x55555a72dc00, beginInfo=..., subpassContents=VK_SUBPASS_CONTENTS_INLINE)
    at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:920
920	    ASSERT(valid());
(gdb) c
Continuing.

Thread 1 "angle_end2end_t" hit Breakpoint 5, rx::vk::priv::CommandBuffer::endRenderPass (this=0x55555a72dc00) at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:926
926	    ASSERT(mHandle != VK_NULL_HANDLE);
(gdb) c
Continuing.
```

3) Now test creates another FBO and image is sampled by vertex shader.
We see the image already in the correct layout, but previous barrier was only from transfer to fragment shader. Now it is used by vertex shader, so we add excution and memory barrier from transfer to vertex shader.

```
Thread 1 "angle_end2end_t" hit Breakpoint 2, rx::vk::priv::CommandBuffer::pipelineBarrier (this=0x55555a72dc00, srcStageMask=4097, dstStageMask=1032, dependencyFlags=0, 
    memoryBarrierCount=1, memoryBarriers=0x7fffffffb318, bufferMemoryBarrierCount=0, bufferMemoryBarriers=0x0, imageMemoryBarrierCount=1, imageMemoryBarriers=0x55555ad1c770)
    at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:809
809	    ASSERT(valid());
810	    vkCmdPipelineBarrier(mHandle, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount,
811	                         memoryBarriers, bufferMemoryBarrierCount, bufferMemoryBarriers,
812	                         imageMemoryBarrierCount, imageMemoryBarriers);

 (gdb) bt
#0  rx::vk::priv::CommandBuffer::pipelineBarrier (this=0x55555a72dc00, srcStageMask=4097, dstStageMask=1032, dependencyFlags=0, memoryBarrierCount=1, memoryBarriers=0x7fffffffb318, 
    bufferMemoryBarrierCount=0, bufferMemoryBarriers=0x0, imageMemoryBarrierCount=1, imageMemoryBarriers=0x55555ad1c770) at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:809
#1  0x00007ffff687987b in rx::vk::PipelineBarrier::execute (this=0x55555ac2ade0, primary=0x55555a72dc00) at ../../src/libANGLE/renderer/vulkan/vk_helpers.h:680
#2  0x00007ffff6838114 in rx::vk::CommandBufferHelperCommon::executeBarriers (this=0x55555ac2ad00, features=..., commandsState=0x55555a72dbd0)
    at ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp:1668
#3  0x00007ffff6841162 in rx::vk::RenderPassCommandBufferHelper::flushToPrimary (this=0x55555ac2ad00, context=0x55555abfc748, commandsState=0x55555a72dbd0, renderPass=..., 
    framebufferOverride=0x0) at ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp:2833
#4  0x00007ffff65bc0c6 in rx::vk::CommandQueue::flushRenderPassCommands (this=0x55555a72da70, context=0x55555abfc748, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfe900) at ../../src/libANGLE/renderer/vulkan/CommandProcessor.cpp:1357
#5  0x00007ffff68ce118 in rx::vk::Renderer::flushRenderPassCommands (this=0x55555a722e90, context=0x55555abfc748, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfe900) at ../../src/libANGLE/renderer/vulkan/vk_renderer.cpp:5730
#6  0x00007ffff65ffe61 in rx::ContextVk::flushCommandsAndEndRenderPassWithoutSubmit (this=0x55555abfc720, reason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:8011
#7  0x00007ffff65e5fa9 in rx::ContextVk::flushImpl (this=0x55555abfc720, signalSemaphore=0x0, externalFence=0x0, renderPassClosureReason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:7595
#8  0x00007ffff65e29e5 in rx::ContextVk::finishImpl (this=0x55555abfc720, renderPassClosureReason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:7707
#9  0x00007ffff65e6e2a in rx::ContextVk::finish (this=0x55555abfc720, context=0x55555abf8060) at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:1520
#10 0x00007ffff6a4ac1b in gl::Context::finish (this=0x55555abf8060) at ../../src/libANGLE/Context.cpp:2903
#11 0x00007ffff6506df3 in GL_Finish () at ../../src/libGLESv2/entry_points_gles_2_0_autogen.cpp:1367
#12 0x000055555787ee97 in (anonymous namespace)::Texture2DTest::testUploadThenUseInDifferentStages (this=0x55555a71af30, uses=...) at ../../src/tests/gl_tests/TextureTest.cpp:12157
#13 0x0000555557880d55 in (anonymous namespace)::Texture2DTest_UploadThenFSThenNewRPThenVS_Test::TestBody (this=0x55555a71af30) at ../../src/tests/gl_tests/TextureTest.cpp:12213
```

here:

```
srcStageMask is 4097 == 0x1001 == VK_PIPELINE_STAGE_TRANSFER_BIT | VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
dstStageMask is 1032 == 0x408 == VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_VERTEX_SHADER_BIT
(gdb) p *memoryBarriers
$12 = {
  sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
  pNext = 0x0,
  srcAccessMask = 4096 (0x1000, which is VK_ACCESS_2_TRANSFER_WRITE_BIT_KHR),
  dstAccessMask = 32   (0x20, which is VK_ACCESS_2_SHADER_READ_BIT)
}
(gdb) p imageMemoryBarriers[0]            
$13 = {
  sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
  pNext = 0x0,
  srcAccessMask = 0,
  dstAccessMask = 384,
  oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
  newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
  srcQueueFamilyIndex = 0,
  dstQueueFamilyIndex = 0,
  image = 0x280000000028,
  subresourceRange = {
    aspectMask = 1,
    baseMipLevel = 0,
    levelCount = 1,
    baseArrayLayer = 0,
    layerCount = 1
  }
}
```

Note that VkImge `0x2f000000002f` is not in the `imageMemoryBarriers`, since there is no need to do layout change.
And then we we start render pass and submit and then hit the error

```
(gdb) c
Continuing.

Thread 1 "angle_end2end_t" hit Breakpoint 4, rx::vk::priv::CommandBuffer::beginRenderPass (this=0x55555a72dc00, beginInfo=..., subpassContents=VK_SUBPASS_CONTENTS_INLINE)
    at ../../src/libANGLE/renderer/vulkan/vk_wrapper.h:920
920	    ASSERT(valid());
(gdb) c
Continuing.
../../src/tests/test_utils/ANGLETest.cpp:65: Failure
vk_renderer.cpp:829 (DebugUtilsMessenger): [ SYNC-HAZARD-READ-AFTER-WRITE ] Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x300000000030, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xe4d96472 | vkCmdDraw():  Hazard READ_AFTER_WRITE for VkImageView 0x300000000030[], in VkCommandBuffer 0x55555aad6ec0[], and VkPipeline 0x3c000000003c[], VkDescriptorSet 0x400000000040[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 0. Access info (usage: SYNC_VERTEX_SHADER_SHADER_SAMPLED_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_SHADER_BINDING_TABLE_READ|SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, command: vkCmdPipelineBarrier, seq_no: 3, VkImage 0x2f000000002f[], VkImage 0x2c000000002c[], reset_no: 1).
                            Object: 0x300000000030 (type = Image View(14))


(gdb) bt
...
#6  0x00007ffff68bcd78 in rx::vk::(anonymous namespace)::DebugUtilsMessenger (messageSeverity=VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT, messageTypes=2, callbackData=0x7fffffff9bf0, 
    userData=0x55555a722e90) at ../../src/libANGLE/renderer/vulkan/vk_renderer.cpp:829
#7  0x00007fffe4721bd0 in DebugReport::DebugLogMsg (this=0x55555a7d8020, msg_flags=8, objects=..., 
    message=0x55555ad0dcd0 "vkCmdDraw():  Hazard READ_AFTER_WRITE for VkImageView 0x300000000030[], in VkCommandBuffer 0x55555aad6ec0[], and VkPipeline 0x3c000000003c[], VkDescriptorSet 0x400000000040[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 0. Access info (usage: SYNC_VERTEX_SHADER_SHADER_SAMPLED_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_SHADER_BINDING_TABLE_READ|SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, command: vkCmdPipelineBarrier, seq_no: 3, VkImage 0x2f000000002f[], VkImage 0x2c000000002c[], reset_no: 1).", text_vuid=0x7fffe31e68f7 "SYNC-HAZARD-READ-AFTER-WRITE")
    at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/error_message/logging.cpp:238
#8  0x00007fffe4724e1a in DebugReport::LogMsg (this=0x55555a7d8020, msg_flags=8, objects=..., loc=0x7fffffffaa90, vuid_text=std::string_view of length 28: "SYNC-HAZARD-READ-AFTER-WRITE", 
    format=0x7fffe2edd261 "Hazard %s for %s, in %s, and %s, %s, type: %s, imageLayout: %s, binding #%u, index %u. Access info %s.", argptr=0x7fffffffa1b0)
    at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/error_message/logging.cpp:646
#9  0x00007fffe3acf27a in ValidationObject::LogError (this=0x55555abe32c0, vuid_text=std::string_view of length 28: "SYNC-HAZARD-READ-AFTER-WRITE", objlist=..., loc=..., 
    format=0x7fffe2edd261 "Hazard %s for %s, in %s, and %s, %s, type: %s, imageLayout: %s, binding #%u, index %u. Access info %s.")
    at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/vulkan/generated/chassis.h:2314
#10 0x00007fffe425ed1e in CommandBufferAccessContext::ValidateDispatchDrawDescriptorSet (this=0x55555aadc2e0, pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS, loc=...)
    at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/sync/sync_commandbuffer.cpp:368
#11 0x00007fffe42e8224 in SyncValidator::PreCallValidateCmdDraw (this=0x55555abe32c0, commandBuffer=0x55555aad6ec0, vertexCount=6, instanceCount=1, firstVertex=0, firstInstance=0, 
    error_obj=...) at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/sync/sync_validation.cpp:1373
#12 0x00007fffe43dd997 in vulkan_layer_chassis::CmdDraw (commandBuffer=0x55555aad6ec0, vertexCount=6, instanceCount=1, firstVertex=0, firstInstance=0)
    at ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/vulkan/generated/chassis.cpp:3246
#13 0x00007ffff66c2a29 in rx::vk::priv::SecondaryCommandBuffer::executeCommands (this=0x55555ac2b1b0, primary=0x55555a72dc00)
    at ../../src/libANGLE/renderer/vulkan/SecondaryCommandBuffer.cpp:409
#14 0x00007ffff68414bd in rx::vk::RenderPassCommandBufferHelper::flushToPrimary (this=0x55555ac2ae70, context=0x55555abfcab8, commandsState=0x55555a72dbd0, renderPass=..., 
    framebufferOverride=0x0) at ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp:2873
#15 0x00007ffff65bc0c6 in rx::vk::CommandQueue::flushRenderPassCommands (this=0x55555a72da70, context=0x55555abfcab8, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfec70) at ../../src/libANGLE/renderer/vulkan/CommandProcessor.cpp:1357
#16 0x00007ffff68ce118 in rx::vk::Renderer::flushRenderPassCommands (this=0x55555a722e90, context=0x55555abfcab8, protectionType=rx::vk::ProtectionType::Unprotected, 
    priority=egl::ContextPriority::Medium, renderPass=..., framebufferOverride=0x0, renderPassCommands=0x55555abfec70) at ../../src/libANGLE/renderer/vulkan/vk_renderer.cpp:5730
#17 0x00007ffff65ffe61 in rx::ContextVk::flushCommandsAndEndRenderPassWithoutSubmit (this=0x55555abfca90, reason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:8011
#18 0x00007ffff65e5fa9 in rx::ContextVk::flushImpl (this=0x55555abfca90, signalSemaphore=0x0, externalFence=0x0, renderPassClosureReason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:7595
#19 0x00007ffff65e29e5 in rx::ContextVk::finishImpl (this=0x55555abfca90, renderPassClosureReason=rx::RenderPassClosureReason::GLFinish)
    at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:7707
#20 0x00007ffff65e6e2a in rx::ContextVk::finish (this=0x55555abfca90, context=0x55555abf8500) at ../../src/libANGLE/renderer/vulkan/ContextVk.cpp:1520
#21 0x00007ffff6a4ac1b in gl::Context::finish (this=0x55555abf8500) at ../../src/libANGLE/Context.cpp:2903
```

Note that we did insert a VkPipelineBarrier and srcStageMask has VK_PIPELINE_STAGE_TRANSFER_BIT and dstStageMask has VK_PIPELINE_STAGE_VERTEX_SHADER_BIT and memoryBarrier is properly set as well. We did not list the image in the imageMemoryBarriers argument, which seems is where the syncVal looking at. But the memoryBarrier should apply to the image as well, and syncVal seems not taking account to it.

**Comment by cclao** [comment]
Discussed internally, We think the SyncVal might be right: For the second memory barrier I inserted, the first scope does not include the layout change for the image. I am going to take back the bug for now.
