### ISSUE TITLE
Non-deterministic WRITE_AFTER_PRESENT when multiple windows render and present in parallel

### ISSUE THREAD

**Issue by knokko** [KhronosGroup/Vulkan-ValidationLayers#8576]
**Environment:**
 - OS: Windows (also happens on Ubuntu)
 - GPU and driver version: 3070 Ti driver version 561.9.0.0
 - SDK or header version if building from repo: 1.3.290
 - Options enabled (synchronization, best practices, etc.): synchronization

**Describe the Issue**

I have a test application that manages 2 (or more) windows in parallel. Each window has its own thread where it records command buffers, submits them, and presents. This causes the validation layer to **sometimes** spit out the following two errors:

For the 'fill' window (which only fills the window with the color pink):
```
SYNC-HAZARD-WRITE-AFTER-PRESENT(ERROR / SPEC): msgNum: 1123218669 - Validation Error: [ SYNC-HAZARD-WRITE-AFTER-PRESENT ] Object 0: handle = 0x23aa750c810, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x42f2f4ed | vkQueueSubmit():  Hazard WRITE_AFTER_PRESENT for entry 0, VkCommandBuffer 0x23aa77fad90[FillWindowLoopBuffer1], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 16). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_PRESENTED_SYNCVAL, write_barriers: 0, queue: VkQueue 0x23aa750c810[], submit: 41, batch: 0, batch_tag: 140, vkQueuePresentKHR present_tag:140, pSwapchains[0]: VkSwapchainKHR 0xcad092000000000d[Swapchain-FillWindow1], image_index: 0image: VkImage 0x967dd1000000000e[SwapchainImage-FillWindow0]).
    Objects: 1
        [0] 0x23aa750c810, type: 4, name: NULL
```

For the 'spin' window (which renders a spinning triangle):
```
SYNC-HAZARD-WRITE-AFTER-PRESENT(ERROR / SPEC): msgNum: 1123218669 - Validation Error: [ SYNC-HAZARD-WRITE-AFTER-PRESENT ] Object 0: handle = 0x23aa750c810, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x42f2f4ed | vkQueueSubmit():  Hazard WRITE_AFTER_PRESENT for entry 0, VkCommandBuffer 0x23aa7765e80[SpinWindowLoopBuffer0], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 20). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_PRESENTED_SYNCVAL, write_barriers: 0, queue: VkQueue 0x23aa750c810[], submit: 40, batch: 0, batch_tag: 139, vkQueuePresentKHR present_tag:139, pSwapchains[0]: VkSwapchainKHR 0xd175b40000000013[Swapchain-SpinWindow1], image_index: 0image: VkImage 0x9fde6b0000000014[SwapchainImage-SpinWindow0]).
    Objects: 1
        [0] 0x23aa750c810, type: 4, name: NULL
```

The weirdest part is that the errors stop coming **as soon as I close 1 of the windows**. I think this is a bug because the windows operate independently (and therefor the appearance of validation errors should not depend on whether there is another window):
- they have their own swapchain
- they have their own fences and semaphores
- they have their own command pools

They *do* share a queue, but it's accessed under mutual exclusion. (And if I remove this mutual exclusion, it reports a completely justified `UNASSIGNED-Threading-MultipleThreads-Write`.) Also, when they use separate queues, these weird validation errors also appear.

I attached an api dump of my application as file to this issue. You can find the validation errors by searching "WRITE_AFTER_PRESENT". The api dump clearly shows that some `vkQueueSubmit` calls cause a validation error, but most of them do not. I have not yet managed to figure out why some sequences of calls in the dump lead to validation errors, but others do not.

Since this is a pretty complex issue, it would be an enormous amount of work to make a minimal reproducible example. I can however share my (test) application that causes the errors: https://github.com/knokko/vk-boiler/tree/potential-validation-bug
It unfortunately requires Java (21) to run, but this can easily be installed on Ubuntu with `sudo apt install openjdk-21-jdk`. The README shows the instructions to run the (pre-built) program.

The problem generates plenty of validation errors per second on both of my computers, but I can't be absolutely sure that this will also happen on other computers.

**Expected behavior**

- If my application is bugged (I don't think so, but I'm never sure), the validation errors should be consistent and deterministic
- If my application is correct, no validation errors should be reported

[dump.txt](https://github.com/user-attachments/files/17089607/dump.txt)

**Comment by artem-lunarg** [comment]
@knokko I'm trying to reproduce this (sorry, it took some time), but I get some errors when run the jar file or when trying to run from IDE. If you have opportunity could you check if this is still an issue? Any insights what I am doing wrong (previously I could run your samples).

> Exception in thread "main" java.lang.OutOfMemoryError: Out of stack space.
        at org.lwjgl.system.MemoryStack.nmalloc(MemoryStack.java:322)
        at org.lwjgl.vulkan.VkExtensionProperties.malloc(VkExtensionProperties.java:210)
        at org.lwjgl.vulkan.VkInstance.getAvailableDeviceExtensions(VkInstance.java:82)
        at org.lwjgl.vulkan.VkInstance.getInstanceCapabilities(VkInstance.java:45)
        at org.lwjgl.vulkan.VkInstance.<init>(VkInstance.java:29)
        at com.github.knokko.boiler.builders.BoilerBuilder.lambda$static$0(BoilerBuilder.java:56)
        at com.github.knokko.boiler.builders.BoilerInstanceBuilder.createInstance(BoilerInstanceBuilder.java:128)
        at com.github.knokko.boiler.builders.BoilerBuilder.build(BoilerBuilder.java:627)
        at com.github.knokko.boiler.samples.MultipleWindows.main(MultipleWindows.java:40)

**Comment by knokko** [comment]
@artem-lunarg Thanks for looking into this! You did nothing wrong: you encountered an old bug in the Java Vulkan bindings that has been fixed in the meantime. I put an improved version on https://github.com/knokko/vk-boiler/tree/potential-validation-bug-modernized

(This sample used to work when the device extensions listed by `vkEnumerateDeviceExtensionproperties` would fit on a 64KB stack, but modern graphics drivers support more extensions than they did in 2024... The fixed version of the Java bindings no longer tries to put them on a tiny 64 KB stack.)

It looks like this potential validation bug hasn't been fixed in the meantime, but the error message is slightly different now:
```
Validation Error: [ SYNC-HAZARD-WRITE-AFTER-PRESENT ] | MessageID = 0x42f2f4ed
vkQueueSubmit(): WRITE_AFTER_PRESENT hazard detected. vkCmdPipelineBarrier (from VkCommandBuffer 0x79a570013a60[SpinWindowLoopBuffer0] submitted on the current VkQueue 0x79a615527e50) writes to VkImage 0x260000000026[Swapchain-SpinWindow1Image1], which was previously written by vkQueuePresentKHR (submitted on VkQueue 0x79a615527e50). 
No sufficient synchronization is present to ensure that a layout transition does not conflict with a prior swapchain present operation.
Objects: 2
    [0] VkQueue 0x79a615527e50
    [1] VkCommandBuffer 0x79a570013a60[SpinWindowLoopBuffer0]
```

I must admit I did not check the new error in detail, but it is still just as random/non-deterministic as it used to be (it only happens in a few % of the frames, and only when multiple windows are being rendered in parallel).

**Comment by artem-lunarg** [comment]
@knokko It turns out this was fixed recently by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/11958. The latest SDK still reports the error but it's validation error free in the latest code. Let me know if something does not work.

**Comment by knokko** [comment]
@artem-lunarg  I tried the VVL build from https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/24743956231

The error is not completely gone, but it did become much less common:
- Before that PR, this sample would spam errors when it has only 2 windows
- After this PR, the sample needs ~6 windows to spam the error

(A larger number of windows results in a larger probability to hit the validation error.)

I pushed some changes to my branch to make it easier to reproduce:
- You can add the `fail-on-validation` command-line argument to make the program abort upon encountering the first validation error.
- You can add an extra window by clicking on the blue window with the spinning triangle.
- I updated dump.txt to show the new API dump (see below).

Also, the validation error changed a bit: it now complains about `vkQueuePresentKHR` -> `vkQueuePresentKHR`. The new error is:
```
vkQueuePresentKHR(): WRITE_AFTER_PRESENT hazard detected. vkQueuePresentKHR presents swapchain image 0 (VkImage 0x2ef00000002ef[Swapchain-Extra(0.6, 0.1, 0.5)1Image0] from VkSwapchainKHR 0x2ee00000002ee[Swapchain-Extra(0.6, 0.1, 0.5)1]), which was previously written by another vkQueuePresentKHR command. 
No sufficient synchronization is present to ensure that a swapchain present operation does not conflict with a prior swapchain present operation.
```
As far as I can see, all the necessary pipeline barriers are present, so I think this is still a false positive.

The last *successful* queue present of the problematic swapchain image (image 0):
```
Thread 6, Frame 826:
vkQueuePresentKHR(queue, pPresentInfo) returns VkResult VK_SUCCESS (0):
    queue:                          VkQueue = 0x7a17849cb770
    pPresentInfo:                   const VkPresentInfoKHR* = 0x7a1658010f00:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR (1000001001)
        pNext:                          const void* = NULL
        waitSemaphoreCount:             uint32_t = 1
        pWaitSemaphores:                const VkSemaphore* = 0x7a1658010ef8
            pWaitSemaphores[0]:             const VkSemaphore = 0x2f500000002f5 [Swapchain-Extra(0.6, 0.1, 0.5)1Present0]
        swapchainCount:                 uint32_t = 1
        pSwapchains:                    const VkSwapchainKHR* = 0x7a1658010ef0
            pSwapchains[0]:                 const VkSwapchainKHR = 0x2ee00000002ee [Swapchain-Extra(0.6, 0.1, 0.5)1]
        pImageIndices:                  const uint32_t* = 0x7a1658010eec
            pImageIndices[0]:               const uint32_t = 0
        pResults:                       VkResult* = 0x7a1658010ee8
            pResults[0]:                    VkResult = VK_SUCCESS (0)
```

The last queue present with *another* swapchain image (image 3):
```
Thread 6, Frame 843:
vkQueuePresentKHR(queue, pPresentInfo) returns VkResult VK_SUCCESS (0):
    queue:                          VkQueue = 0x7a17849cb770
    pPresentInfo:                   const VkPresentInfoKHR* = 0x7a1658010f00:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR (1000001001)
        pNext:                          const void* = NULL
        waitSemaphoreCount:             uint32_t = 1
        pWaitSemaphores:                const VkSemaphore* = 0x7a1658010ef8
            pWaitSemaphores[0]:             const VkSemaphore = 0x2fd00000002fd [Swapchain-Extra(0.6, 0.1, 0.5)1Present3]
        swapchainCount:                 uint32_t = 1
        pSwapchains:                    const VkSwapchainKHR* = 0x7a1658010ef0
            pSwapchains[0]:                 const VkSwapchainKHR = 0x2ee00000002ee [Swapchain-Extra(0.6, 0.1, 0.5)1]
        pImageIndices:                  const uint32_t* = 0x7a1658010eec
            pImageIndices[0]:               const uint32_t = 3
        pResults:                       VkResult* = 0x7a1658010ee8
            pResults[0]:                    VkResult = VK_SUCCESS (0)
```

The last frame of the problematic swapchain image (image 0). I believe these two pipeline barriers should be sufficient, yet the final `vkQueuePresentKHR` fails with `VK_ERROR_VALIDATION_FAILED`, with the above validation error.
```
Thread 6, Frame 844:
vkAcquireNextImageKHR(device, swapchain, timeout, semaphore, fence, pImageIndex) returns VkResult VK_SUCCESS (0):
    device:                         VkDevice = 0x7a1784883170
    swapchain:                      VkSwapchainKHR = 0x2ee00000002ee [Swapchain-Extra(0.6, 0.1, 0.5)1]
    timeout:                        uint64_t = 100000000
    semaphore:                      VkSemaphore = 0x2fa00000002fa [Extra(0.6, 0.1, 0.5)Acquire2]
    fence:                          VkFence = 0
    pImageIndex:                    uint32_t* = 0
```

```
Thread 6, Frame 845:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x7a1658012520 [FillWindowLoopBuffer0]
    srcStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dstStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dependencyFlags:                VkDependencyFlags = 0
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = NULL
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = NULL
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7a1658010f78
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7a1658010f78:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE)
            dstAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_UNDEFINED (0)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            srcQueueFamilyIndex:            uint32_t = 4294967295
            dstQueueFamilyIndex:            uint32_t = 4294967295
            image:                          VkImage = 0x2ef00000002ef [Swapchain-Extra(0.6, 0.1, 0.5)1Image0]
            subresourceRange:               VkImageSubresourceRange = 0:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1
```

```
Thread 6, Frame 845:
vkCmdClearColorImage(commandBuffer, image, imageLayout, pColor, rangeCount, pRanges) returns void:
    commandBuffer:                  VkCommandBuffer = 0x7a1658012520 [FillWindowLoopBuffer0]
    image:                          VkImage = 0x2ef00000002ef [Swapchain-Extra(0.6, 0.1, 0.5)1Image0]
    imageLayout:                    VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
    pColor:                         const VkClearColorValue* = 0x7a1658010f68 (Union):
        float32:                        float[4] = 0x7a1658010f68
            float32[0]:                     float = 0.555994
            float32[1]:                     float = 0.0882708
            float32[2]:                     float = 0.488735
            float32[3]:                     float = 1
        int32:                          int32_t[4] = 0x7a1658010f68
            int32[0]:                       int32_t = 1057904026
            int32[1]:                       int32_t = 1035257688
            int32[2]:                       int32_t = 1056586630
            int32[3]:                       int32_t = 1065353216
        uint32:                         uint32_t[4] = 0x7a1658010f68
            uint32[0]:                      uint32_t = 1057904026
            uint32[1]:                      uint32_t = 1035257688
            uint32[2]:                      uint32_t = 1056586630
            uint32[3]:                      uint32_t = 1065353216
    rangeCount:                     uint32_t = 1
    pRanges:                        const VkImageSubresourceRange* = 0x7a1658010f44
        pRanges[0]:                     const VkImageSubresourceRange = 0x7a1658010f44:
            aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
            baseMipLevel:                   uint32_t = 0
            levelCount:                     uint32_t = 1
            baseArrayLayer:                 uint32_t = 0
            layerCount:                     uint32_t = 1
```

```
Thread 6, Frame 845:
vkCmdPipelineBarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers) returns void:
    commandBuffer:                  VkCommandBuffer = 0x7a1658012520 [FillWindowLoopBuffer0]
    srcStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dstStageMask:                   VkPipelineStageFlags = 8192 (VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT)
    dependencyFlags:                VkDependencyFlags = 0
    memoryBarrierCount:             uint32_t = 0
    pMemoryBarriers:                const VkMemoryBarrier* = NULL
    bufferMemoryBarrierCount:       uint32_t = 0
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = NULL
    imageMemoryBarrierCount:        uint32_t = 1
    pImageMemoryBarriers:           const VkImageMemoryBarrier* = 0x7a1658010f78
        pImageMemoryBarriers[0]:        const VkImageMemoryBarrier = 0x7a1658010f78:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER (45)
            pNext:                          const void* = NULL
            srcAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            dstAccessMask:                  VkAccessFlags = 0 (VK_ACCESS_NONE)
            oldLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL (7)
            newLayout:                      VkImageLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR (1000001002)
            srcQueueFamilyIndex:            uint32_t = 4294967295
            dstQueueFamilyIndex:            uint32_t = 4294967295
            image:                          VkImage = 0x2ef00000002ef [Swapchain-Extra(0.6, 0.1, 0.5)1Image0]
            subresourceRange:               VkImageSubresourceRange = 0:
                aspectMask:                     VkImageAspectFlags = 1 (VK_IMAGE_ASPECT_COLOR_BIT)
                baseMipLevel:                   uint32_t = 0
                levelCount:                     uint32_t = 1
                baseArrayLayer:                 uint32_t = 0
                layerCount:                     uint32_t = 1
```

```
Thread 6, Frame 850:
vkQueueSubmit(queue, submitCount, pSubmits, fence) returns VkResult VK_SUCCESS (0):
    queue:                          VkQueue = 0x7a17849cb770
    submitCount:                    uint32_t = 1
    pSubmits:                       const VkSubmitInfo* = 0x7a1658010ef8
        pSubmits[0]:                    const VkSubmitInfo = 0x7a1658010ef8:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_SUBMIT_INFO (4)
            pNext:                          const void* = NULL
            waitSemaphoreCount:             uint32_t = 1
            pWaitSemaphores:                const VkSemaphore* = 0x7a1658010ef0
                pWaitSemaphores[0]:             const VkSemaphore = 0x2fa00000002fa [Extra(0.6, 0.1, 0.5)Acquire2]
            pWaitDstStageMask:              const VkPipelineStageFlags* = 0x7a1658010eec
                pWaitDstStageMask[0]:           const VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
            commandBufferCount:             uint32_t = 1
            pCommandBuffers:                const VkCommandBuffer* = 0x7a1658010ee0
                pCommandBuffers[0]:             const VkCommandBuffer = 0x7a1658012520 [FillWindowLoopBuffer0]
            signalSemaphoreCount:           uint32_t = 1
            pSignalSemaphores:              const VkSemaphore* = 0x7a1658010ed8
                pSignalSemaphores[0]:           const VkSemaphore = 0x2f500000002f5 [Swapchain-Extra(0.6, 0.1, 0.5)1Present0]
    fence:                          VkFence = 0x2eb00000002eb [FillWindowLoopCommandFence-0]
```

```
Thread 6, Frame 855:
vkQueuePresentKHR(queue, pPresentInfo) returns VkResult VK_ERROR_VALIDATION_FAILED (-1000011001):
    queue:                          VkQueue = 0x7a17849cb770
    pPresentInfo:                   const VkPresentInfoKHR* = 0x7a1658010f00:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR (1000001001)
        pNext:                          const void* = NULL
        waitSemaphoreCount:             uint32_t = 1
        pWaitSemaphores:                const VkSemaphore* = 0x7a1658010ef8
            pWaitSemaphores[0]:             const VkSemaphore = 0x2f500000002f5 [Swapchain-Extra(0.6, 0.1, 0.5)1Present0]
        swapchainCount:                 uint32_t = 1
        pSwapchains:                    const VkSwapchainKHR* = 0x7a1658010ef0
            pSwapchains[0]:                 const VkSwapchainKHR = 0x2ee00000002ee [Swapchain-Extra(0.6, 0.1, 0.5)1]
        pImageIndices:                  const uint32_t* = 0x7a1658010eec
            pImageIndices[0]:               const uint32_t = 0
        pResults:                       VkResult* = 0x7a1658010ee8
            pResults[0]:                    VkResult = VK_SUCCESS (0)
```

By the way, I don't have permission to re-open issues here.

**Comment by artem-lunarg** [comment]
@knokko I'm trying to get intuition what's going on by debuggin VVL code, but also could you answer few quick questions:
1) Do you create a separate thread for each window/swapchain?
2) How do you manage  semaphores that are signaled by QueueSubmit and waited on by QueuePresent? Do you re-use them (if yes, what's the algorithm) or recreate them?

**Comment by knokko** [comment]
1. Yes: the main thread polls GLFW events, and there is 1 separate rendering/background thread per window. The queue submissions and queue presents happen on the rendering/background threads. They all use the same queue, and a mutex makes sure that they don't present/submit at the same time. (Removing the mutex causes a completely justified spam of validation errors.)
2. Every window has 1 present semaphore per swapchain image and 1 acquire semaphore per frame in flight. They are created when they are first needed, and are destroyed when the window is destroyed.

Your question (2) did give me a brilliant observation: the validation errors go away if I use a fence rather than semaphore in `vkAcquireNextImageKHR`! I can make the application validation-error-free even with 14 windows (and probably more, but I didn't try that).

**Comment by artem-lunarg** [comment]
> Every window has 1 present semaphore per swapchain image and 1 acquire semaphore per frame in flight. They are created when they are first needed, and are destroyed when the window is destroyed.

People often make mistakes with QueuePresent wait semaphores. Is it only one semaphore? I mean you present on the first frame, do you use the same semaphore on the next one? Could you provide a pseudocode of a frame loop of a single windows (to represent sequence of acquire, submit and present and how semaphores are used)

**Comment by knokko** [comment]
It is 1 present semaphore *per swapchain image*. I rarely use the same present semaphore in two subsequent queue presents: only in the hypothetical case that `vkAcquireNextImageKHR` gives the same image index twice in a row, which did *not* happen. (According to the API dump, the acquired image indices were simply 0,1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, ...)

I use 1 acquire semaphore per *frame in flight* (3 fif's in this example). The first `vkAcquireNextImageKHR` call uses acquire semaphore 0, the next call uses acquire semaphore 1, the third call uses acquire semaphore 3, the fourth call uses acquire semaphore 4, etc...

Basically
```
acquireSemaphores[numFramesInFlight];
commandFences[numFramesInFlight];
commandPools[numFramesInFlight];
commandBuffers[numFramesInFlight];
// just 1 command buffer per command pool
swapchainImages[numImages];

sharedMutex; // shared with all other window render threads

currentFrame = 0;

while (window is open) {
  frameIndex = currentFrame % numFramesInFlight;
  imageIndex = acquireSwapchainImage(acquireSemaphores[frameIndex]);

  awaitAndResetFence(commandFences[frameIndex]);
  resetCommandPool(commandPools[frameIndex];

  recordRenderCommandsAndBarriers(commandsBuffers[frameIndex], swapchainImages[imageIndex]);

  while holding sharedMutex:
    queueSubmit(commandBuffers[frameIndex], acquireSemaphores[frameIndex], presentSemaphores[imageIndex]);

  while holding sharedMutex:
    queuePresent(presentSemaphores[imageIndex]);

  currentFrame += 1;
}
```

I would be surprised if this were the culprit, since VVL didn't need 6 windows and 800 frames to catch my swapchain mistakes in the past.

My best guess is that VVL is somewhere comparing the last `vkQueuePresentKHR` with swapchain image 0 instead of the last `vkQueuePresentKHR` with swapchain image 0 of **of swapchain X**. I would guess that a particular interleaving of the render loops of the windows is what 'tricks' VVL.
Or... even worse... an actual data race in VVL that happens because e.g. one window calls `vkQueuePresentKHR` while another window calls `vkAcquireNextImageKHR`.
This is all speculation though, and I can only guess unless I know on which exact function invocations the `WRITE-AFTER-PRESENT` is based.

I *think* that the problem here lies on VVL rather than my own code, just because I couldn't find anything out of the ordinary in the API dump. Note that the full dump can be found here: https://github.com/knokko/vk-boiler/blob/potential-validation-bug-modernized/dump.txt
(Unfortunately, it is not very easy to read such dumps when there are ~6 threads running concurrently. Still, searching on the name of one of the swapchains in a light-weight text editor like vim does the job. Searching for "VK_ERROR_VALI" should find the problematic queue present.)

**Comment by artem-lunarg** [comment]
Thanks for the pseudocode, I'll try to write a test that does something similar.

> I use 1 acquire semaphore per frame in flight 

That's correct approach

> It is 1 present semaphore per swapchain image. 

Yes, that's correct too (btw, it also handles when acquire returns the same index twice in a row, happens on nvidia hardware sometimes, especialy during the first frames).

> awaitAndResetFence(commandFences[frameIndex]);

Is it `queueSubmit` from the pseudocode that signals the fence?

**Comment by artem-lunarg** [comment]
I'm writing a test and I had to adjust the beginning of the loop - the fence wait should go before AcquireNextImage, otherwise per-frame acquire semaphroe can still be in use (and validation error reports this). I assume that's how the app works and it's just a pseudocode inaccuracy:

 frameIndex = currentFrame % numFramesInFlight;
 awaitAndResetFence(commandFences[frameIndex]);
 imageIndex = acquireSwapchainImage(acquireSemaphores[frameIndex]);

**Comment by artem-lunarg** [comment]
The first version of the test ready: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/2fb49b342ec54080b87a9decc79d31d3a4d5b597

On my machine it does not reproduce the issue. The only difference with pseudocode is I don't use command buffers. The assumption was the issue somehwere in the semaphore/synchronization part. I'm going to add a second variant which submits a command buffer.

**Comment by artem-lunarg** [comment]
Good news. A test with command buffers reproduces the issue: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/07de55ad21ea6a97297805036f885f1e763fcf64

**Comment by knokko** [comment]
> I'm writing a test and I had to adjust the beginning of the loop - the fence wait should go before AcquireNextImage, otherwise per-frame acquire semaphroe can still be in use (and validation error reports this). I assume that's how the app works and it's just a pseudocode inaccuracy:
> 
> frameIndex = currentFrame % numFramesInFlight; awaitAndResetFence(commandFences[frameIndex]); imageIndex = acquireSwapchainImage(acquireSemaphores[frameIndex]);

This was not a pseudocode inaccuracy: my app really does it in this order, and without any validation errors being reported. I am trying to remember why it works like this...

**Comment by artem-lunarg** [comment]
Well, maybe you have some mechanism that allows to do this. For a simple test I fixed the order, but this also does not matter much now, the error is reproduciable!

**Comment by knokko** [comment]
You're totally right: I just realized I have framesInFlight + 1 acquire semaphores.

**Comment by artem-lunarg** [comment]
@knokko The latest code has a fix, feel free to try.

**Comment by knokko** [comment]
I cannot reproduce the issue with the latest build, not even with 10+ windows, so it looks like you fixed it completely!

Congratulations with fixing this one, this is definitely the most disgusting false positive I found so far!

**Comment by artem-lunarg** [comment]
>  this is definitely the most disgusting false positive

Thanks, this means a lot
